let data = [
["Ultimate Fighting Championship",
1713045600000,
'',
[
  {
    fighterA: 'Justin Gaethje',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/16421-justin-gaethje',
    rankA: '#3',
    recordA: '25-4-0 ',
    weight: '155',
    recordB: ' 25-7-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/12723-max-holloway-lil-evil',
    fighterB: 'Max Holloway'
  },
  {
    fighterA: 'Jiří Procházka',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/34779-jiri-prochazka',
    rankA: '#3',
    recordA: '29-4-1 ',
    weight: '205',
    recordB: ' 14-3-0',
    rankB: '#6',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/75026-aleksandar-rakic',
    fighterB: 'Aleksandar Rakić'
  },
  {
    fighterA: 'Charles Oliveira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/charles-oliveira-do-bronx',
    rankA: '#2',
    recordA: '34-9-0 ',
    weight: '155',
    recordB: ' 21-3-0',
    rankB: '#4',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/115752-arman-tsarukyan',
    fighterB: 'Arman Tsarukyan'
  },
  {
    fighterA: 'Weili Zhang',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/83443-weili-zhang',
    rankA: '#1',
    recordA: '24-3-0 ',
    weight: '115',
    recordB: ' 17-3-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/12602-xiao-nan-yang-fury',
    fighterB: 'Xiaonan Yan'
  },
  {
    fighterA: 'Calvin Kattar',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/calvin-kattar-the-boston-finisher',
    rankA: '#9',
    recordA: '23-7-0 ',
    weight: '145',
    recordB: ' 23-4-0',
    rankB: '#15',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/aljamain-sterling',
    fighterB: 'Aljamain Sterling'
  },
  {
    fighterA: 'Bo Nickal',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/244627-bo-nickal',
    rankA: '#36',
    recordA: '5-0-0 ',
    weight: '185',
    recordB: ' 10-5-0',
    rankB: '#54',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/169818-cody-brundage',
    fighterB: 'Cody Brundage'
  },
  {
    fighterA: 'Deiveson Figueiredo',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/76553-deiveson-alcantra-daico',
    rankA: '#18',
    recordA: '22-3-1 ',
    weight: '135',
    recordB: ' 14-5-0',
    rankB: '#30',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/21780-cody-garbrandt-no-love',
    fighterB: 'Cody Garbrandt'
  },
  {
    fighterA: 'Bobby Green',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/bobby-green-king',
    rankA: '#11',
    recordA: '31-15-1 ',
    weight: '155',
    recordB: ' 37-17-0',
    rankB: '#30',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/jim-miller',
    fighterB: 'Jim Miller'
  },
  {
    fighterA: 'Holly Holm',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/18698-holly-holm-hottie',
    rankA: '#6',
    recordA: '15-6-0 ',
    weight: '135',
    recordB: ' 16-1-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/34265-kayla-harrison',
    fighterB: 'Kayla Harrison'
  },
  {
    fighterA: 'Sodiq Yusuff',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/58362-sodiq-yusuff',
    rankA: '#11',
    recordA: '13-3-0 ',
    weight: '145',
    recordB: ' 23-6-0',
    rankB: '#17',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/85643-diego-lopes',
    fighterB: 'Diego Lopes'
  },
  {
    fighterA: 'Jéssica Andrade',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/34388-jessica-andrade-bate-estaca',
    rankA: '#5',
    recordA: '25-12-0 ',
    weight: '115',
    recordB: ' 17-3-2',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/81799-marina-rodriguez',
    fighterB: 'Marina Rodriguez'
  }
]
,"UFC 300",
"7",
"Pay Per View | Prelims: ESPN"
],
["Ultimate Fighting Championship",
1712440800000,
'',
[
  {
    fighterA: 'Marvin Vettori',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/50533-marvin-vettori',
    rankA: '#6',
    recordA: '19-6-1 ',
    weight: '185',
    recordB: ' 23-5-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/91516-brendan-allen',
    fighterB: 'Brendan Allen'
  },
  {
    fighterA: 'Alexander Hernandez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/46253-alexander-hernandez',
    rankA: '#71',
    recordA: '14-7-0 ',
    weight: '145',
    recordB: ' 22-6-1',
    rankB: '#20',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/39377-damon-jackson',
    fighterB: 'Damon Jackson'
  },
  {
    fighterA: 'Norma Dumont',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/139271-norma-dumont-viana',
    rankA: '#3',
    recordA: '10-2-0 ',
    weight: '135',
    recordB: ' 10-4-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/germaine-de-randamie-the-iron-lady',
    fighterB: 'Germaine de Randamie'
  },
  {
    fighterA: 'Łukasz Brzeski',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90654-ukasz-brzeski',
    rankA: '#99',
    recordA: '8-4-1 ',
    weight: '265',
    recordB: ' 11-0-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/267496-valter-rui-the-clean-monster',
    fighterB: 'Valter Walker'
  },
  {
    fighterA: 'Ignacio Bahamondes',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/105800-ignacio-carabantes',
    rankA: '#38',
    recordA: '14-5-0 ',
    weight: '155',
    recordB: ' 20-11-0',
    rankB: '#53',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/38606-christos-giagos-the-spartan',
    fighterB: 'Christos Giagos'
  },
  {
    fighterA: 'Melissa Tonya Mullins',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/188856-melissa-mullins',
    rankA: '#17',
    recordA: '6-0-0 ',
    weight: '135',
    recordB: ' 7-1-0',
    rankB: '#18',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/297105-nora-cornolle',
    fighterB: 'Nora Cornolle'
  },
  {
    fighterA: 'Seung Woo Choi',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/108867-seung-woo-choi',
    rankA: '#39',
    recordA: '11-6-0 ',
    weight: '145',
    recordB: ' 19-9-1',
    rankB: '#65',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/93065-morgan-charriere',
    fighterB: 'Morgan Charriere'
  },
  {
    fighterA: 'César Almeida',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/126015-csar-almeida',
    rankA: '#127',
    recordA: '4-0-0 ',
    weight: '185',
    recordB: ' 11-5-0',
    rankB: '#60',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/65199-joshua-fremd',
    fighterB: 'Josh Fremd'
  },
  {
    fighterA: 'Cynthia Calvillo',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/25471-cynthia-calvillo',
    rankA: '#39',
    recordA: '9-6-1 ',
    weight: '115',
    recordB: ' 9-1-0',
    rankB: '#25',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/140642-pierangela-rodriguez',
    fighterB: 'Piera Rodriguez'
  },
  {
    fighterA: 'Alatengheili',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/57170-ala-tengheili',
    rankA: '#47',
    recordA: '16-9-2 ',
    weight: '135',
    recordB: ' 24-4-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/48149-victor-striker',
    fighterB: 'Victor Hugo'
  },
  {
    fighterA: 'Trevor Peek',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/60331-trevor-peek',
    rankA: '#90',
    recordA: '9-1-0 ',
    weight: '155',
    recordB: ' 8-2-0',
    rankB: '#104',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/179091-charlie-campbell',
    fighterB: 'Charlie Campbell'
  },
  {
    fighterA: 'Jose Johnson',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/110739-jose-johnson',
    rankA: '#75',
    recordA: '16-8-0 ',
    weight: '125',
    recordB: ' 17-1-0',
    rankB: '#3',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/192343-lucas-rocha-fenomeno',
    fighterB: 'Lucas Rocha'
  }
]
,"UFC Fight Night",
"9",
"ESPN+"
],
["Ultimate Fighting Championship",
1712440800000,
'',
[
  {
    fighterA: 'Marvin Vettori',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/50533-marvin-vettori',
    rankA: '#6',
    recordA: '19-6-1 ',
    weight: '185',
    recordB: ' 23-5-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/91516-brendan-allen',
    fighterB: 'Brendan Allen'
  },
  {
    fighterA: 'Alexander Hernandez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/46253-alexander-hernandez',
    rankA: '#71',
    recordA: '14-7-0 ',
    weight: '145',
    recordB: ' 22-6-1',
    rankB: '#20',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/39377-damon-jackson',
    fighterB: 'Damon Jackson'
  },
  {
    fighterA: 'Norma Dumont',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/139271-norma-dumont-viana',
    rankA: '#3',
    recordA: '10-2-0 ',
    weight: '135',
    recordB: ' 10-4-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/germaine-de-randamie-the-iron-lady',
    fighterB: 'Germaine de Randamie'
  },
  {
    fighterA: 'Łukasz Brzeski',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90654-ukasz-brzeski',
    rankA: '#99',
    recordA: '8-4-1 ',
    weight: '265',
    recordB: ' 11-0-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/267496-valter-rui-the-clean-monster',
    fighterB: 'Valter Walker'
  },
  {
    fighterA: 'Ignacio Bahamondes',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/105800-ignacio-carabantes',
    rankA: '#38',
    recordA: '14-5-0 ',
    weight: '155',
    recordB: ' 20-11-0',
    rankB: '#53',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/38606-christos-giagos-the-spartan',
    fighterB: 'Christos Giagos'
  },
  {
    fighterA: 'Melissa Tonya Mullins',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/188856-melissa-mullins',
    rankA: '#17',
    recordA: '6-0-0 ',
    weight: '135',
    recordB: ' 7-1-0',
    rankB: '#18',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/297105-nora-cornolle',
    fighterB: 'Nora Cornolle'
  },
  {
    fighterA: 'Seung Woo Choi',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/108867-seung-woo-choi',
    rankA: '#39',
    recordA: '11-6-0 ',
    weight: '145',
    recordB: ' 19-9-1',
    rankB: '#65',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/93065-morgan-charriere',
    fighterB: 'Morgan Charriere'
  },
  {
    fighterA: 'César Almeida',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/126015-csar-almeida',
    rankA: '#127',
    recordA: '4-0-0 ',
    weight: '185',
    recordB: ' 11-5-0',
    rankB: '#60',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/65199-joshua-fremd',
    fighterB: 'Josh Fremd'
  },
  {
    fighterA: 'Cynthia Calvillo',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/25471-cynthia-calvillo',
    rankA: '#39',
    recordA: '9-6-1 ',
    weight: '115',
    recordB: ' 9-1-0',
    rankB: '#25',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/140642-pierangela-rodriguez',
    fighterB: 'Piera Rodriguez'
  },
  {
    fighterA: 'Alatengheili',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/57170-ala-tengheili',
    rankA: '#47',
    recordA: '16-9-2 ',
    weight: '135',
    recordB: ' 24-4-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/48149-victor-striker',
    fighterB: 'Victor Hugo'
  },
  {
    fighterA: 'Trevor Peek',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/60331-trevor-peek',
    rankA: '#90',
    recordA: '9-1-0 ',
    weight: '155',
    recordB: ' 8-2-0',
    rankB: '#104',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/179091-charlie-campbell',
    fighterB: 'Charlie Campbell'
  },
  {
    fighterA: 'Jose Johnson',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/110739-jose-johnson',
    rankA: '#75',
    recordA: '16-8-0 ',
    weight: '125',
    recordB: ' 17-1-0',
    rankB: '#3',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/192343-lucas-rocha-fenomeno',
    fighterB: 'Lucas Rocha'
  }
]
,"UFC Fight Night",
"9",
"ESPN+"
],
["Ultimate Fighting Championship",
1711839600000,
'',
[
  {
    fighterA: 'Erin Blanchfield',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/167460-erin-blanchfield',
    rankA: '#4',
    recordA: '12-1-0 ',
    weight: '125',
    recordB: ' 11-1-0',
    rankB: '#3',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/136168-manon-fiorot',
    fighterB: 'Manon Fiorot'
  },
  {
    fighterA: 'Vicente Luque',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/16651-vicente-luque',
    rankA: '#11',
    recordA: '22-9-1 ',
    weight: '170',
    recordB: ' 17-6-0',
    rankB: '#24',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/55022-joaquin-buckley',
    fighterB: 'Joaquin Buckley'
  },
  {
    fighterA: 'Virna Jandiroba',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/56622-virna-jandiroba',
    rankA: '#6',
    recordA: '19-3-0 ',
    weight: '115',
    recordB: ' 12-3-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/133312-lupita-godinez',
    fighterB: 'Lupita Godinez'
  },
  {
    fighterA: 'Andre Petroski',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/123353-andre-petroski',
    rankA: '#35',
    recordA: '10-2-0 ',
    weight: '185',
    recordB: ' 7-3-0',
    rankB: '#52',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/111323-jacob-malkoun',
    fighterB: 'Jacob Malkoun'
  },
  {
    fighterA: 'Bruno Silva',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/59819-bruno-silva-blindado',
    rankA: '#27',
    recordA: '23-10-0 ',
    weight: '185',
    recordB: ' 15-7-0',
    rankB: '#46',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/chris-weidman',
    fighterB: 'Chris Weidman'
  },
  {
    fighterA: 'Chidi Njokuani',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/chidi-njokuani',
    rankA: '#42',
    recordA: '22-10-0 ',
    weight: '185',
    recordB: ' 13-5-1',
    rankB: '#100',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/54321-rhys-mckee',
    fighterB: 'Rhys McKee'
  },
  {
    fighterA: 'Alonzo Menifield',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/69032-alonzo-menifield',
    rankA: '#15',
    recordA: '15-3-1 ',
    weight: '205',
    recordB: ' 9-1-0',
    rankB: '#19',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/203365-carlos-ulberg-mr-marvelous',
    fighterB: 'Carlos Ulberg'
  },
  {
    fighterA: 'Connor Matthews',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/14969-connor-matthews',
    rankA: '#14',
    recordA: '7-1-0 ',
    weight: '145',
    recordB: ' 11-4-0',
    rankB: '#135',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/131561-dennis-buzukia',
    fighterB: 'Dennis Buzukja'
  },
  {
    fighterA: 'Angel Pacheco',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/20352-angel-pacheco',
    rankA: '#1',
    recordA: '7-2-0 ',
    weight: '135',
    recordB: ' 8-1-0',
    rankB: '#104',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/152507-caolan-loughran',
    fighterB: 'Caolán Loughran'
  },
  {
    fighterA: 'Julio Arce',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/30552-julio-arce',
    rankA: '#42',
    recordA: '18-6-0 ',
    weight: '145',
    recordB: ' 11-4-0',
    rankB: '#69',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/60086-herbert-burns',
    fighterB: 'Herbert Burns'
  },
  {
    fighterA: 'Nursulton Ruziboev',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/89891-nursultan-ruziboev-black',
    rankA: '#24',
    recordA: '35-8-2 ',
    weight: '185',
    recordB: ' 9-1-0',
    rankB: '#66',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/188574-sedriques-dumas',
    fighterB: 'Sedriques Dumas'
  },
  {
    fighterA: 'Ibo Aslan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/151252-ibo-aslan',
    rankA: '#11',
    recordA: '12-1-0 ',
    weight: '205',
    recordB: ' 8-3-0',
    rankB: '#69',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/115015-anton-turkalj',
    fighterB: 'Anton Turkalj'
  },
  {
    fighterA: 'Melissa Gatto',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/164565-melissa-gatto',
    rankA: '#28',
    recordA: '8-2-2 ',
    weight: '125',
    recordB: ' 8-0-0',
    rankB: '#41',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/227991-viktoria-dudakova',
    fighterB: 'Victoria Dudakova'
  },
  {
    fighterA: 'Bill Algeo',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/25872-william-algeo-honey-badger',
    rankA: '#24',
    recordA: '18-7-0 ',
    weight: '145',
    recordB: ' 15-5-1',
    rankB: '#45',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/21458-kyle-nelson-the-monster',
    fighterB: 'Kyle Nelson'
  }
]
,"UFC Fight Night",
"7",
"ESPN+"
],
["Ultimate Fighting Championship",
1711234800000,
'',
[
  {
    fighterA: 'Amanda Ribas',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/74330-amanda-ribas',
    rankA: '#16',
    recordA: '12-4-0 ',
    weight: '125',
    recordB: ' 11-6-0',
    rankB: '#30',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/39227-rose-namajunas-the-riveter',
    fighterB: 'Rose Namajunas'
  },
  {
    fighterA: 'Ricardo Ramos',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/56182-ricardo-ramos-carcacinha',
    rankA: '#37',
    recordA: '16-5-0 ',
    weight: '145',
    recordB: ' 28-11-0',
    rankB: '#32',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/18497-julian-erosa',
    fighterB: 'Julian Erosa'
  },
  {
    fighterA: 'Davey Grant',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/18815-david-grant',
    rankA: '#25',
    recordA: '13-7-0 ',
    weight: '135',
    recordB: ' 19-9-0',
    rankB: '#81',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/cody-gibson',
    fighterB: 'Cody Gibson'
  },
  {
    fighterA: 'Edmen Shahbazyan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/142325-edmen-shahbazyan',
    rankA: '#31',
    recordA: '12-4-0 ',
    weight: '185',
    recordB: ' 7-2-0',
    rankB: '#66',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/29725-aj-dobson',
    fighterB: 'AJ Dobson'
  },
  {
    fighterA: 'Montserrat Rendon',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/213856-montse-rendon',
    rankA: '#22',
    recordA: '6-0-0 ',
    weight: '135',
    recordB: ' 8-1-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/229363-dariya-zheleznyakova',
    fighterB: 'Darya Zheleznyakova'
  },
  {
    fighterA: 'Stephanie Luciano',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/180757-stephanie-luciano-rondinha',
    rankA: '#28',
    recordA: '5-1-1 ',
    weight: '115',
    recordB: ' 5-1-0',
    rankB: '#84',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/209968-shauna-bannon',
    fighterB: 'Shauna Bannon'
  },
  {
    fighterA: 'Luis Pajuelo',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/201946-luis-pajuelo',
    rankA: '#18',
    recordA: '8-1-0 ',
    weight: '145',
    recordB: ' 15-5-0',
    rankB: '#44',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/98371-fernando-padilla',
    fighterB: 'Fernando Padilla'
  },
  {
    fighterA: 'Steven Nguyen',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37300-steven-nguyen',
    rankA: '#17',
    recordA: '9-1-0 ',
    weight: '145',
    recordB: ' 13-5-1',
    rankB: '#142',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/112766-jarno-errens',
    fighterB: 'Jarno Errens'
  },
  {
    fighterA: 'Trey Ogden',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90133-trey-ogden',
    rankA: '#86',
    recordA: '16-6-0 ',
    weight: '155',
    recordB: ' 20-7-0',
    rankB: '#91',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/27877-kurt-holobaugh',
    fighterB: 'Kurt Holobaugh'
  },
  {
    fighterA: 'Billy Quarantillo',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/42701-billy-quarantillo',
    rankA: '#19',
    recordA: '18-5-0 ',
    weight: '145',
    recordB: ' 17-6-0',
    rankB: '#70',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/36548-gabriel-miranda-fly',
    fighterB: 'Gabriel Miranda'
  },
  {
    fighterA: 'Mohammed Usman',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/156538-mohammed-usman',
    rankA: '#30',
    recordA: '10-2-0 ',
    weight: '265',
    recordB: ' 8-0-0',
    rankB: '#45',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/124944-michael-parkin',
    fighterB: 'Mick Parkin'
  },
  {
    fighterA: 'Junior Tafa',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/242095-junior-tafa',
    rankA: '#42',
    recordA: '5-1-0 ',
    weight: '265',
    recordB: ' 9-1-0',
    rankB: '#35',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/215578-karl-williams',
    fighterB: 'Karl Williams'
  },
  {
    fighterA: 'Payton Talbott',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/181513-payton-talbout',
    rankA: '#89',
    recordA: '7-0-0 ',
    weight: '135',
    recordB: ' 9-1-0',
    rankB: '#43',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/112520-cameron-saaiman',
    fighterB: 'Cameron Saaiman'
  },
  {
    fighterA: 'Igor da Silva',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/229458-igor-da-silva-severino-cogumelo',
    rankA: '#19',
    recordA: '8-0-0 ',
    weight: '125',
    recordB: ' 7-0-0',
    rankB: '#18',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/129386-andr-lima-mascote',
    fighterB: 'André Lima'
  }
]
,"UFC Fight Night",
"10",
"ESPN+"
],
["Ultimate Fighting Championship",
1710025200000,
'',
[
  {
    fighterA: "Sean O'Malley",
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/68186-sean-omalley',
    rankA: '#1',
    recordA: '17-1-0 ',
    weight: '135',
    recordB: ' 23-8-1',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/48144-marlon-vera-chito',
    fighterB: 'Marlon Vera'
  },
  {
    fighterA: 'Dustin Poirier',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/dustin-poirier-the-diamond',
    rankA: '#6',
    recordA: '29-8-0 ',
    weight: '155',
    recordB: ' 13-1-0',
    rankB: '#13',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/212810-benoit-saint-denis',
    fighterB: 'Benoit Saint-Denis'
  },
  {
    fighterA: 'Gilbert Burns',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/31168-gilbert-burns-durinho',
    rankA: '#3',
    recordA: '22-6-0 ',
    weight: '170',
    recordB: ' 16-2-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/119831-jack-della-maddalena',
    fighterB: 'Jack Della Maddalena'
  },
  {
    fighterA: 'Petr Yan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90075-petr-yan',
    rankA: '#5',
    recordA: '16-5-0 ',
    weight: '135',
    recordB: ' 21-7-1',
    rankB: '#4',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/47836-yadong-song',
    fighterB: 'Yadong Song'
  },
  {
    fighterA: 'Kevin Holland',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/35757-kevin-holland',
    rankA: '#12',
    recordA: '25-10-0 ',
    weight: '170',
    recordB: ' 21-2-0',
    rankB: '#33',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/21208-michael-page',
    fighterB: 'Michael Page'
  },
  {
    fighterA: 'Pedro Munhoz',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/5243-pedro-munoz-pedrinho',
    rankA: '#16',
    recordA: '20-8-0 ',
    weight: '135',
    recordB: ' 11-2-0',
    rankB: '#22',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/93501-kyler-phillips',
    fighterB: 'Kyler Phillips'
  },
  {
    fighterA: 'CJ Vergara',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/38340-carlos-vergara',
    rankA: '#26',
    recordA: '12-4-1 ',
    weight: '125',
    recordB: ' 18-2-0',
    rankB: '#20',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/127726-khamzat-sakalov',
    fighterB: 'Asu Almabaev'
  },
  {
    fighterA: 'Katlyn Chookagian',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37760-katlyn-chookagian',
    rankA: '#5',
    recordA: '18-5-0 ',
    weight: '125',
    recordB: ' 13-2-0',
    rankB: '#6',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/143925-maycee-barber',
    fighterB: 'Maycee Barber'
  },
  {
    fighterA: 'Curtis Blaydes',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/51080-curtis-blaydes',
    rankA: '#6',
    recordA: '17-4-0 ',
    weight: '265',
    recordB: ' 20-2-0',
    rankB: '#5',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/151690-jailton-junior-malhadinho',
    fighterB: 'Jailton Almeida'
  },
  {
    fighterA: 'Mateusz Gamrot',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/26305-mateusz-gamrot',
    rankA: '#5',
    recordA: '23-2-0 ',
    weight: '155',
    recordB: ' 32-15-0',
    rankB: '#23',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/rafael-dos-anjos',
    fighterB: 'Rafael dos Anjos'
  },
  {
    fighterA: 'Michel Pereira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/55575-michel-pereira',
    rankA: '#21',
    recordA: '29-11-0 ',
    weight: '185',
    recordB: ' 19-6-0',
    rankB: '#40',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/61212-michal-oleksiejczuk',
    fighterB: 'Michał Oleksiejczuk'
  },
  {
    fighterA: 'Robelis Despaigne',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/339509-robelis-despaigne',
    rankA: '#66',
    recordA: '4-0-0 ',
    weight: '265',
    recordB: ' 15-7-0',
    rankB: '#85',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/86139-josh-parisian',
    fighterB: 'Josh Parisian'
  },
  {
    fighterA: 'Joanne Wood',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/22500-joanne-calderwood',
    rankA: '#19',
    recordA: '16-8-0 ',
    weight: '125',
    recordB: ' 11-5-0',
    rankB: '#24',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/73990-marina-moroz',
    fighterB: 'Maryna Moroz'
  },
  {
    fighterA: 'Philipe Lins',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/9874-felipe-lins-felipao',
    rankA: '#27',
    recordA: '17-5-0 ',
    weight: '205',
    recordB: ' 17-9-1',
    rankB: '#23',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/34843-ion-cutelaba',
    fighterB: 'Ion Cutelaba'
  }
]
,"UFC 299",
"9",
"Pay Per View | Prelims: ESPN"
],
["Ultimate Fighting Championship",
1709420400000,
'',
[
  {
    fighterA: 'Jairzinho Rozenstruik',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/62467-jair-rozenstruik-bigi-boy',
    rankA: '#13',
    recordA: '13-5-0 ',
    weight: '265',
    recordB: ' 12-0-0',
    rankB: '#18',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/201352-shamil-gaziev',
    fighterB: 'Shamil Gaziev'
  },
  {
    fighterA: 'Vitor Petrino',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/158172-vitor-petrino',
    rankA: '#22',
    recordA: '10-0-0 ',
    weight: '205',
    recordB: ' 10-4-0',
    rankB: '#33',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/55878-tyson-pedro',
    fighterB: 'Tyson Pedro'
  },
  {
    fighterA: 'Eryk Anders',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/30666-eryk-anders',
    rankA: '#52',
    recordA: '15-8-0 ',
    weight: '185',
    recordB: ' 13-10-0',
    rankB: '#84',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/38304-jamie-pickett',
    fighterB: 'Jamie Pickett'
  },
  {
    fighterA: 'Alex Perez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/alex-perez',
    rankA: '#10',
    recordA: '24-7-0 ',
    weight: '125',
    recordB: ' 10-0-0',
    rankB: '#8',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/120417-muhammad-mokaev',
    fighterB: 'Muhammad Mokaev'
  },
  {
    fighterA: 'Matt Schnell',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/29221-matt-schnell',
    rankA: '#11',
    recordA: '16-7-0 ',
    weight: '125',
    recordB: ' 11-1-0',
    rankB: '#12',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/132326-stephen-erceg',
    fighterB: 'Steve Erceg'
  },
  {
    fighterA: 'Umar Nurmagomedov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/134206-omar-nurmagomedov',
    rankA: '#8',
    recordA: '16-0-0 ',
    weight: '135',
    recordB: ' 17-1-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/192704-bekzat-almakhan',
    fighterB: 'Bekzat Almakhan'
  },
  {
    fighterA: 'Joel Alvarez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/97013-joel-alvarez',
    rankA: '#17',
    recordA: '20-3-0 ',
    weight: '155',
    recordB: ' 20-4-1',
    rankB: '#33',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/102094-ludovit-klein',
    fighterB: 'Ľudovít Klein'
  },
  {
    fighterA: 'Vinicius Oliveira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/50927-vinicius-prego',
    rankA: '#3',
    recordA: '19-3-0 ',
    weight: '135',
    recordB: ' 12-2-0',
    rankB: '#127',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/98157-yanis-ghemmouri',
    fighterB: 'Yanis Ghemmouri'
  },
  {
    fighterA: 'Javid Basharat',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/116280-javid-bashrat',
    rankA: '#24',
    recordA: '14-0-0 ',
    weight: '135',
    recordB: ' 10-2-0',
    rankB: '#39',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/25314-aiemann-zahabi',
    fighterB: 'Aiemann Zahabi'
  },
  {
    fighterA: 'Mohammad Yahya',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/66362-mohammad-yahya',
    rankA: '#163',
    recordA: '12-4-0 ',
    weight: '155',
    recordB: ' 8-2-0',
    rankB: '#264',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/117074-brendan-marotte',
    fighterB: 'Brendon Marotte'
  },
  {
    fighterA: 'Loik Radzhabov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/95647-loik-razdhabov-jaguar-paw',
    rankA: '#67',
    recordA: '17-5-1 ',
    weight: '155',
    recordB: ' 15-3-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/77145-abdul-kareem-al-selwady',
    fighterB: 'A. Al-Selwady'
  },
  {
    fighterA: 'Julia Polastri',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/168315-julia-polastri',
    rankA: '#3',
    recordA: '12-3-0 ',
    weight: '115',
    recordB: ' 7-0-0',
    rankB: '#44',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/174069-josefine-lindgren-knutsson-little-thunder',
    fighterB: 'Josefine Knutsson'
  },
  {
    fighterA: 'Christian Leroy Duncan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/116334-christian-duncan',
    rankA: '#53',
    recordA: '9-1-0 ',
    weight: '185',
    recordB: ' 11-4-0',
    rankB: '#70',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/149468-claudio-ribeiro',
    fighterB: 'Claudio Ribeiro'
  }
]
,"UFC Fight Night",
"7",
"ESPN+"
],
["Ultimate Fighting Championship",
1708815600000,
'',
[
  {
    fighterA: 'Brandon Moreno',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/27833-brandon-moreno-the-assassin',
    rankA: '#2',
    recordA: '21-7-2 ',
    weight: '125',
    recordB: ' 15-7-0',
    rankB: '#5',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/25031-brandon-royval',
    fighterB: 'Brandon Royval'
  },
  {
    fighterA: 'Yair Rodriguez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/70995-yair-rodriguez',
    rankA: '#3',
    recordA: '18-4-0 ',
    weight: '145',
    recordB: ' 15-3-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/40994-brian-ortega',
    fighterB: 'Brian Ortega'
  },
  {
    fighterA: 'Yazmin Jauregui',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/207769-yasmine-jauregui',
    rankA: '#26',
    recordA: '10-1-0 ',
    weight: '115',
    recordB: ' 8-5-0',
    rankB: '#28',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/140901-sam-hughes',
    fighterB: 'Sam Hughes'
  },
  {
    fighterA: 'Manuel Torres',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/194607-manuel-torres-el-loco',
    rankA: '#56',
    recordA: '14-2-0 ',
    weight: '155',
    recordB: ' 11-1-0',
    rankB: '#76',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/68484-chris-duncan',
    fighterB: 'Chris Duncan'
  },
  {
    fighterA: 'Raul Rosas Jr.',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/94654-raul-rosas',
    rankA: '#57',
    recordA: '8-1-0 ',
    weight: '135',
    recordB: ' 12-3-0',
    rankB: '#63',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/46586-ricky-turcios',
    fighterB: 'Ricky Turcios'
  },
  {
    fighterA: 'Daniel Zellhuber',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/156784-daniel-olvera-zellhuber-zellhuber',
    rankA: '#62',
    recordA: '14-1-0 ',
    weight: '155',
    recordB: ' 12-1-0',
    rankB: '#67',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/230239-francisco-prado',
    fighterB: 'Francisco Prado'
  },
  {
    fighterA: 'Edgar Cháirez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/80020-edgar-chaidez',
    rankA: '#72',
    recordA: '10-5-0 ',
    weight: '125',
    recordB: ' 11-5-0',
    rankB: '#56',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/162924-daniel-lacerda-miojo',
    fighterB: 'Daniel Lacerda'
  },
  {
    fighterA: 'Victor Altamirano',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/101415-victor-altamirano',
    rankA: '#31',
    recordA: '12-3-0 ',
    weight: '125',
    recordB: ' 7-1-0',
    rankB: '#42',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/247470-felipe-dos-santos-lipe-detona',
    fighterB: 'Felipe dos Santos'
  },
  {
    fighterA: 'Jesus Aguilar',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/108511-jesus-aguilar',
    rankA: '#40',
    recordA: '9-2-0 ',
    weight: '125',
    recordB: ' 10-2-0',
    rankB: '#69',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/218144-matheus-mendonca-bocao',
    fighterB: 'Mateus Mendonça'
  },
  {
    fighterA: 'Luis Rodríguez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/165024-luis-rodrguez-lazyboy',
    rankA: '#9',
    recordA: '16-2-0 ',
    weight: '125',
    recordB: ' 19-4-0',
    rankB: '#55',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/104652-denis-bondar',
    fighterB: 'Denys Bondar'
  },
  {
    fighterA: 'Muhammad Naimov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/136098-muhammadjon-naimov',
    rankA: '#33',
    recordA: '10-2-0 ',
    weight: '145',
    recordB: ' 9-2-0',
    rankB: '#135',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/126790-erik-silva',
    fighterB: 'Erik Silva'
  },
  {
    fighterA: 'Cristian Quiñonez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/69208-christian-quionez-el-taylon',
    rankA: '#65',
    recordA: '18-4-0 ',
    weight: '135',
    recordB: ' 17-5-0',
    rankB: '#32',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/30448-raoni-barcellos',
    fighterB: 'Raoni Barcelos'
  },
  {
    fighterA: 'Claudio Puelles',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/53808-claudio-puelles',
    rankA: '#29',
    recordA: '12-3-0 ',
    weight: '155',
    recordB: ' 14-4-0',
    rankB: '#40',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/119061-fares-ziam',
    fighterB: 'Fares Ziam'
  }
]
,"UFC Fight Night",
"7",
"ESPN+"
],
["Ultimate Fighting Championship",
1708212600000,
'',
[
  {
    fighterA: 'Alexander Volkanovski',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/41705-alex-volkanski',
    rankA: '#62',
    recordA: '26-3-0 ',
    weight: '145',
    recordB: ' 14-0-0',
    rankB: '#3',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/129278-ilia-topuria',
    fighterB: 'Ilia Topuria'
  },
  {
    fighterA: 'Robert Whittaker',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/17398-robert-whittaker',
    rankA: '#5',
    recordA: '24-7-0 ',
    weight: '185',
    recordB: ' 14-2-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/64306-paulo-henrique-costa-borrachinha',
    fighterB: 'Paulo Costa'
  },
  {
    fighterA: 'Geoff Neal',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/20058-geoffrey-neal',
    rankA: '#8',
    recordA: '15-5-0 ',
    weight: '170',
    recordB: ' 13-0-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/171377-ian-garry',
    fighterB: 'Ian Machado Garry'
  },
  {
    fighterA: 'Merab Dvalishvili',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/47934-merab-dvalishvili',
    rankA: '#2',
    recordA: '16-4-0 ',
    weight: '135',
    recordB: ' 16-3-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/42359-henry-cejudo',
    fighterB: 'Henry Cejudo'
  },
  {
    fighterA: 'Anthony Hernandez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/41538-anthony-hernandez',
    rankA: '#14',
    recordA: '11-2-0 ',
    weight: '185',
    recordB: ' 12-2-0',
    rankB: '#23',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/138424-roman-kopylov',
    fighterB: 'Roman Kopylov'
  },
  {
    fighterA: 'Amanda Lemos',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/87845-amanda-lemos-amandinha',
    rankA: '#3',
    recordA: '13-3-1 ',
    weight: '115',
    recordB: ' 13-4-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/134267',
    fighterB: 'Mackenzie Dern'
  },
  {
    fighterA: 'Marcos Rogério de Lima',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/marcos-rogerio-de-lima-pezao',
    rankA: '#16',
    recordA: '21-9-1 ',
    weight: '265',
    recordB: ' 7-3-0',
    rankB: '#26',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/152336-justin-tafa',
    fighterB: 'Justin Tafa'
  },
  {
    fighterA: 'Rinya Nakamura',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/296781-tomoya-nakamura',
    rankA: '#58',
    recordA: '8-0-0 ',
    weight: '135',
    recordB: ' 11-3-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/43109-carlos-vera',
    fighterB: 'Carlos Vera'
  },
  {
    fighterA: 'Mingyang Zhang',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/102827-mingyang-zhang',
    rankA: '#1',
    recordA: '16-6-0 ',
    weight: '205',
    recordB: ' 15-5-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/119779-brendson-ribeiro-zyzz',
    fighterB: 'Brendson Ribeiro'
  },
  {
    fighterA: 'Josh Quinlan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/114123-josh-quinlan',
    rankA: '#100',
    recordA: '6-1-0 ',
    weight: '170',
    recordB: ' 7-0-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/222456-danny-barlow',
    fighterB: 'Danny Barlow'
  },
  {
    fighterA: 'Val Woodburn',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/166396-valentine-woodburn',
    rankA: '#141',
    recordA: '7-1-0 ',
    weight: '170',
    recordB: ' 9-2-0',
    rankB: '#12',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/150814-oban-elliot',
    fighterB: 'Oban Elliott'
  },
  {
    fighterA: 'Andrea Lee',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/47916-andrea-lee',
    rankA: '#18',
    recordA: '13-8-0 ',
    weight: '125',
    recordB: ' 12-5-0',
    rankB: '#19',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/116637-miranda-maverick',
    fighterB: 'Miranda Maverick'
  }
]
,"UFC 298",
"7",
"Pay Per View | Prelims: ESPN"
],
["Ultimate Fighting Championship",
1707598800000,
'',
[
  {
    fighterA: 'Jack Hermansson ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/13893-Jack-Hermansson',
    rankA: '#n/a',
    recordA: '',
    weight: '185',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Joe Pyfer'
  },
  {
    fighterA: 'Dan Ige ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/21178-dan-ige',
    rankA: '#n/a',
    recordA: '',
    weight: '145',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Andre Fili'
  },
  {
    fighterA: 'Ihor Potieria ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/91636-igor-poterya',
    rankA: '#n/a',
    recordA: '',
    weight: '185',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Robert Bryczek'
  },
  {
    fighterA: 'Gregory Rodrigues ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/78681-gregory-rodrigues-robocop',
    rankA: '#n/a',
    recordA: '',
    weight: '185',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Brad Tavares'
  },
  {
    fighterA: 'Michael Johnson ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/michael-johnson-the-menace',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Darrius Flowers'
  },
  {
    fighterA: 'Rodolfo Vieira ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/148791-rodolfo-vieira-srour-the-black-belt-hunter',
    rankA: '#n/a',
    recordA: '',
    weight: '185',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Armen Petrosyan'
  },
  {
    fighterA: 'Carlos Prates ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/36554-carlos-prates-carlao',
    rankA: '#n/a',
    recordA: '',
    weight: '170',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Trevin Giles'
  },
  {
    fighterA: 'Bolaji Oki ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/158527-bolaji-oki',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Timmy Cuamba'
  },
  {
    fighterA: 'Loma Lookboonmee ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/174166-looma-lookboonmee',
    rankA: '#n/a',
    recordA: '',
    weight: '115',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Bruna Brasil'
  },
  {
    fighterA: 'Marcin Prachnio ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/51446-marcin-prachnio',
    rankA: '#n/a',
    recordA: '',
    weight: '205',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Devin Clark'
  },
  {
    fighterA: 'Max Griffin ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/25437-max-griffin',
    rankA: '#n/a',
    recordA: '',
    weight: '170',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Jeremiah Wells'
  },
  {
    fighterA: 'Bogdan Guskov ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/136052-bogdan-guskov',
    rankA: '#n/a',
    recordA: '',
    weight: '205',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Zac Pauga'
  },
  {
    fighterA: 'Hyder Amil ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/114216-hyder-amil',
    rankA: '#n/a',
    recordA: '',
    weight: '145',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Fernie Garcia'
  },
  {
    fighterA: 'Daniel Marcos ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/92877-daniel-marcos',
    rankA: '#n/a',
    recordA: '',
    weight: '135',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Aoriqileng'
  }
]
,"UFC Fight Night",
"8",
"ESPN+"
],
]
module.exports = data;
