let data = [
["Ultimate Fighting Championship",
1666490400000,
'',
[
  {
    fighterA: 'Charles Oliveira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/charles-oliveira-do-bronx',
    rankA: '#1',
    recordA: '33-8-0 ',
    weight: '155',
    recordB: ' 22-1-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/40148-islam-makhachev',
    fighterB: 'Islam Makhachev'
  },
  {
    fighterA: 'Aljamain Sterling',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/aljamain-sterling',
    rankA: '#1',
    recordA: '21-3-0 ',
    weight: '135',
    recordB: ' 17-4-0',
    rankB: '#5',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/19126-tj-dillashaw',
    fighterB: 'T.J. Dillashaw'
  },
  {
    fighterA: 'Petr Yan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90075-petr-yan',
    rankA: '#2',
    recordA: '16-3-0 ',
    weight: '135',
    recordB: ' 15-1-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/68186-sean-omalley',
    fighterB: "Sean O'Malley"
  },
  {
    fighterA: 'Beneil Dariush',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/20010-beneil-dariush-benny',
    rankA: '#5',
    recordA: '21-4-1 ',
    weight: '155',
    recordB: ' 21-1-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/26305-mateusz-gamrot',
    fighterB: 'Mateusz Gamrot'
  },
  {
    fighterA: 'Katlyn Chookagian',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37760-katlyn-chookagian',
    rankA: '#2',
    recordA: '18-4-0 ',
    weight: '125',
    recordB: ' 9-1-0',
    rankB: '#6',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/136168-manon-fiorot',
    fighterB: 'Manon Fiorot'
  },
  {
    fighterA: 'Belal Muhammad',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/32797-belal-muhammad',
    rankA: '#4',
    recordA: '21-3-0 ',
    weight: '170',
    recordB: ' 15-0-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/32242-sean-brady',
    fighterB: 'Sean Brady'
  },
  {
    fighterA: 'Makhmud Muradov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/34702-makhmud-muradov',
    rankA: '#25',
    recordA: '25-7-0 ',
    weight: '185',
    recordB: ' 12-1-0',
    rankB: '#30',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/107316-caio-borralho-cara-de-kombi',
    fighterB: 'Caio Borralho'
  },
  {
    fighterA: 'Volkan Oezdemir',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/35488-volkan-oezdemir-cousin',
    rankA: '#8',
    recordA: '18-6-0 ',
    weight: '205',
    recordB: ' 28-9-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/37801-nikita-krylov',
    fighterB: 'Nikita Krylov'
  },
  {
    fighterA: 'Zubaira Tukhugov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/33555-zubair-tukhugov',
    rankA: '#18',
    recordA: '20-5-1 ',
    weight: '145',
    recordB: ' 14-1-0',
    rankB: '#47',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/124782-lucas-de-oliveira-almeida',
    fighterB: 'Lucas Almeida'
  },
  {
    fighterA: 'Yamato Nishikawa',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/153702-yamato-nishikawa',
    rankA: '#2',
    recordA: '21-3-6 ',
    weight: '155',
    recordB: ' 14-4-0',
    rankB: '#63',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/50888-magomed-mustafaev',
    fighterB: 'Magomed Mustafaev'
  },
  {
    fighterA: 'Abubakar Nurmagomedov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/65871-abubakr-nurmagomedov',
    rankA: '#67',
    recordA: '16-3-1 ',
    weight: '170',
    recordB: ' 13-1-0',
    rankB: '#72',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/158874-gadzhi-omargadzhiev',
    fighterB: 'Gadzhi Omargadzhiev'
  },
  {
    fighterA: 'Armen Petrosyan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/198212-armen-petrosyan',
    rankA: '#39',
    recordA: '6-2-0 ',
    weight: '185',
    recordB: ' 6-1-0',
    rankB: '#77',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/29725-aj-dobson',
    fighterB: 'AJ Dobson'
  },
  {
    fighterA: 'Muhammad Mokaev',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/120417-muhammad-mokaev',
    rankA: '#19',
    recordA: '7-0-0 ',
    weight: '125',
    recordB: ' 14-5-0',
    rankB: '#20',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/36176-malcom-gordon',
    fighterB: 'Malcolm Gordon'
  },
  {
    fighterA: 'Lina Länsberg',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/44543-lina-akhtar-lansberg',
    rankA: '#14',
    recordA: '10-6-0 ',
    weight: '135',
    recordB: ' 15-4-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/79637-karolline-rosa-karol',
    fighterB: 'Karol Rosa'
  }
]
,"UFC 280",
"9",
"Pay Per View | Prelims: ESPN"
],
["Ultimate Fighting Championship",
1666490400000,
'',
[
  {
    fighterA: 'Charles Oliveira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/charles-oliveira-do-bronx',
    rankA: '#1',
    recordA: '33-8-0 ',
    weight: '155',
    recordB: ' 22-1-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/40148-islam-makhachev',
    fighterB: 'Islam Makhachev'
  },
  {
    fighterA: 'Aljamain Sterling',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/aljamain-sterling',
    rankA: '#1',
    recordA: '21-3-0 ',
    weight: '135',
    recordB: ' 17-4-0',
    rankB: '#5',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/19126-tj-dillashaw',
    fighterB: 'T.J. Dillashaw'
  },
  {
    fighterA: 'Petr Yan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90075-petr-yan',
    rankA: '#2',
    recordA: '16-3-0 ',
    weight: '135',
    recordB: ' 15-1-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/68186-sean-omalley',
    fighterB: "Sean O'Malley"
  },
  {
    fighterA: 'Beneil Dariush',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/20010-beneil-dariush-benny',
    rankA: '#5',
    recordA: '21-4-1 ',
    weight: '155',
    recordB: ' 21-1-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/26305-mateusz-gamrot',
    fighterB: 'Mateusz Gamrot'
  },
  {
    fighterA: 'Katlyn Chookagian',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37760-katlyn-chookagian',
    rankA: '#2',
    recordA: '18-4-0 ',
    weight: '125',
    recordB: ' 9-1-0',
    rankB: '#6',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/136168-manon-fiorot',
    fighterB: 'Manon Fiorot'
  },
  {
    fighterA: 'Belal Muhammad',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/32797-belal-muhammad',
    rankA: '#4',
    recordA: '21-3-0 ',
    weight: '170',
    recordB: ' 15-0-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/32242-sean-brady',
    fighterB: 'Sean Brady'
  },
  {
    fighterA: 'Makhmud Muradov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/34702-makhmud-muradov',
    rankA: '#25',
    recordA: '25-7-0 ',
    weight: '185',
    recordB: ' 12-1-0',
    rankB: '#30',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/107316-caio-borralho-cara-de-kombi',
    fighterB: 'Caio Borralho'
  },
  {
    fighterA: 'Volkan Oezdemir',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/35488-volkan-oezdemir-cousin',
    rankA: '#8',
    recordA: '18-6-0 ',
    weight: '205',
    recordB: ' 28-9-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/37801-nikita-krylov',
    fighterB: 'Nikita Krylov'
  },
  {
    fighterA: 'Zubaira Tukhugov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/33555-zubair-tukhugov',
    rankA: '#18',
    recordA: '20-5-1 ',
    weight: '145',
    recordB: ' 14-1-0',
    rankB: '#47',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/124782-lucas-de-oliveira-almeida',
    fighterB: 'Lucas Almeida'
  },
  {
    fighterA: 'Yamato Nishikawa',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/153702-yamato-nishikawa',
    rankA: '#2',
    recordA: '21-3-6 ',
    weight: '155',
    recordB: ' 14-4-0',
    rankB: '#63',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/50888-magomed-mustafaev',
    fighterB: 'Magomed Mustafaev'
  },
  {
    fighterA: 'Abubakar Nurmagomedov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/65871-abubakr-nurmagomedov',
    rankA: '#67',
    recordA: '16-3-1 ',
    weight: '170',
    recordB: ' 13-1-0',
    rankB: '#72',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/158874-gadzhi-omargadzhiev',
    fighterB: 'Gadzhi Omargadzhiev'
  },
  {
    fighterA: 'Armen Petrosyan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/198212-armen-petrosyan',
    rankA: '#39',
    recordA: '6-2-0 ',
    weight: '185',
    recordB: ' 6-1-0',
    rankB: '#77',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/29725-aj-dobson',
    fighterB: 'AJ Dobson'
  },
  {
    fighterA: 'Muhammad Mokaev',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/120417-muhammad-mokaev',
    rankA: '#19',
    recordA: '7-0-0 ',
    weight: '125',
    recordB: ' 14-5-0',
    rankB: '#20',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/36176-malcom-gordon',
    fighterB: 'Malcolm Gordon'
  },
  {
    fighterA: 'Lina Länsberg',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/44543-lina-akhtar-lansberg',
    rankA: '#14',
    recordA: '10-6-0 ',
    weight: '135',
    recordB: ' 15-4-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/79637-karolline-rosa-karol',
    fighterB: 'Karol Rosa'
  }
]
,"UFC 280",
"9",
"Pay Per View | Prelims: ESPN"
],
["Ultimate Fighting Championship",
1666490400000,
'',
[
  {
    fighterA: 'Charles Oliveira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/charles-oliveira-do-bronx',
    rankA: '#1',
    recordA: '33-8-0 ',
    weight: '155',
    recordB: ' 22-1-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/40148-islam-makhachev',
    fighterB: 'Islam Makhachev'
  },
  {
    fighterA: 'Aljamain Sterling',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/aljamain-sterling',
    rankA: '#1',
    recordA: '21-3-0 ',
    weight: '135',
    recordB: ' 17-4-0',
    rankB: '#5',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/19126-tj-dillashaw',
    fighterB: 'T.J. Dillashaw'
  },
  {
    fighterA: 'Petr Yan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90075-petr-yan',
    rankA: '#2',
    recordA: '16-3-0 ',
    weight: '135',
    recordB: ' 15-1-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/68186-sean-omalley',
    fighterB: "Sean O'Malley"
  },
  {
    fighterA: 'Beneil Dariush',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/20010-beneil-dariush-benny',
    rankA: '#5',
    recordA: '21-4-1 ',
    weight: '155',
    recordB: ' 21-1-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/26305-mateusz-gamrot',
    fighterB: 'Mateusz Gamrot'
  },
  {
    fighterA: 'Katlyn Chookagian',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37760-katlyn-chookagian',
    rankA: '#2',
    recordA: '18-4-0 ',
    weight: '125',
    recordB: ' 9-1-0',
    rankB: '#6',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/136168-manon-fiorot',
    fighterB: 'Manon Fiorot'
  },
  {
    fighterA: 'Belal Muhammad',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/32797-belal-muhammad',
    rankA: '#4',
    recordA: '21-3-0 ',
    weight: '170',
    recordB: ' 15-0-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/32242-sean-brady',
    fighterB: 'Sean Brady'
  },
  {
    fighterA: 'Makhmud Muradov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/34702-makhmud-muradov',
    rankA: '#25',
    recordA: '25-7-0 ',
    weight: '185',
    recordB: ' 12-1-0',
    rankB: '#30',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/107316-caio-borralho-cara-de-kombi',
    fighterB: 'Caio Borralho'
  },
  {
    fighterA: 'Volkan Oezdemir',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/35488-volkan-oezdemir-cousin',
    rankA: '#8',
    recordA: '18-6-0 ',
    weight: '205',
    recordB: ' 28-9-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/37801-nikita-krylov',
    fighterB: 'Nikita Krylov'
  },
  {
    fighterA: 'Zubaira Tukhugov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/33555-zubair-tukhugov',
    rankA: '#18',
    recordA: '20-5-1 ',
    weight: '145',
    recordB: ' 14-1-0',
    rankB: '#47',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/124782-lucas-de-oliveira-almeida',
    fighterB: 'Lucas Almeida'
  },
  {
    fighterA: 'Yamato Nishikawa',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/153702-yamato-nishikawa',
    rankA: '#2',
    recordA: '21-3-6 ',
    weight: '155',
    recordB: ' 14-4-0',
    rankB: '#63',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/50888-magomed-mustafaev',
    fighterB: 'Magomed Mustafaev'
  },
  {
    fighterA: 'Abubakar Nurmagomedov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/65871-abubakr-nurmagomedov',
    rankA: '#67',
    recordA: '16-3-1 ',
    weight: '170',
    recordB: ' 13-1-0',
    rankB: '#72',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/158874-gadzhi-omargadzhiev',
    fighterB: 'Gadzhi Omargadzhiev'
  },
  {
    fighterA: 'Armen Petrosyan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/198212-armen-petrosyan',
    rankA: '#39',
    recordA: '6-2-0 ',
    weight: '185',
    recordB: ' 6-1-0',
    rankB: '#77',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/29725-aj-dobson',
    fighterB: 'AJ Dobson'
  },
  {
    fighterA: 'Muhammad Mokaev',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/120417-muhammad-mokaev',
    rankA: '#19',
    recordA: '7-0-0 ',
    weight: '125',
    recordB: ' 14-5-0',
    rankB: '#20',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/36176-malcom-gordon',
    fighterB: 'Malcolm Gordon'
  },
  {
    fighterA: 'Lina Länsberg',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/44543-lina-akhtar-lansberg',
    rankA: '#14',
    recordA: '10-6-0 ',
    weight: '135',
    recordB: ' 15-4-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/79637-karolline-rosa-karol',
    fighterB: 'Karol Rosa'
  }
]
,"UFC 280",
"9",
"Pay Per View | Prelims: ESPN"
],
