let data = [
["Ultimate Fighting Championship",
1635651000000,
'',
[
  {
    fighterA: 'Jan Błachowicz',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/jan-blachowicz',
    rankA: '#1',
    recordA: '28-8-0 ',
    weight: '205',
    recordB: ' 32-7-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/glover-teixeira',
    fighterB: 'Glover Teixeira'
  },
  {
    fighterA: 'Petr Yan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90075-petr-yan',
    rankA: '#2',
    recordA: '15-2-0 ',
    weight: '135',
    recordB: ' 14-3-0',
    rankB: '#3',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/32931-cory-sandhagen',
    fighterB: 'Cory Sandhagen'
  },
  {
    fighterA: 'Islam Makhachev',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/40148-islam-makhachev',
    rankA: '#6',
    recordA: '20-1-0 ',
    weight: '155',
    recordB: ' 21-10-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/18854-daniel-hooker',
    fighterB: 'Dan Hooker'
  },
  {
    fighterA: 'Alexander Volkov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/alexander-volkov',
    rankA: '#6',
    recordA: '33-9-0 ',
    weight: '265',
    recordB: ' 22-6-0',
    rankB: '#8',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/34449-marcin-tybura-tybur',
    fighterB: 'Marcin Tybura'
  },
  {
    fighterA: 'Jingliang Li',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/jing-liang-li-the-leech',
    rankA: '#11',
    recordA: '18-6-0 ',
    weight: '170',
    recordB: ' 9-0-0',
    rankB: '#34',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/188143-khamzat-girikhanov',
    fighterB: 'Khamzat Chimaev'
  },
  {
    fighterA: 'Magomed Ankalaev',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/83405-magomed-ankalaev',
    rankA: '#8',
    recordA: '15-1-0 ',
    weight: '205',
    recordB: ' 17-5-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/35488-volkan-oezdemir-cousin',
    fighterB: 'Volkan Oezdemir'
  },
  {
    fighterA: 'Amanda Ribas',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/74330-amanda-ribas',
    rankA: '#11',
    recordA: '10-2-0 ',
    weight: '115',
    recordB: ' 17-2-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/56622-virna-jandiroba',
    fighterB: 'Virna Jandiroba'
  },
  {
    fighterA: 'Zubaira Tukhugov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/33555-zubair-tukhugov',
    rankA: '#27',
    recordA: '19-5-1 ',
    weight: '145',
    recordB: ' 15-3-0',
    rankB: '#39',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/56182-ricardo-ramos-carcacinha',
    fighterB: 'Ricardo Ramos'
  },
  {
    fighterA: 'Albert Duraev',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/18658-albert-duraev',
    rankA: '#59',
    recordA: '14-3-0 ',
    weight: '185',
    recordB: ' 8-1-0',
    rankB: '#77',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/138424-roman-kopylov',
    fighterB: 'Roman Kopylov'
  },
  {
    fighterA: 'Elizeu Zaleski',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/28131-elizeu-zaleski-capoeira',
    rankA: '#25',
    recordA: '22-7-0 ',
    weight: '170',
    recordB: ' 8-0-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/212810-benoit-saint-denis',
    fighterB: 'Benoit Saint-Denis'
  },
  {
    fighterA: 'Michał Oleksiejczuk',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/61212-michal-oleksiejczuk',
    rankA: '#24',
    recordA: '15-4-0 ',
    weight: '205',
    recordB: ' 14-0-0',
    rankB: '#35',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/66739-shamil-gamzatov',
    fighterB: 'Shamil Gamzatov'
  },
  {
    fighterA: 'Makwan Amirkhani',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/33134-makwan-amirkhani-tsingis-khan',
    rankA: '#33',
    recordA: '16-6-0 ',
    weight: '145',
    recordB: ' 10-0-1',
    rankB: '#34',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/84753-lerone-murphy',
    fighterB: 'Lerone Murphy'
  },
  {
    fighterA: 'Yaozong Hu',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/162606-yaozong-hu',
    rankA: '#183',
    recordA: '3-2-0 ',
    weight: '185',
    recordB: ' 6-1-0',
    rankB: '#96',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/123353-andre-petroski',
    fighterB: 'Andre Petroski'
  },
  {
    fighterA: 'Damir Ismagulov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/81591-damir-ismagulov',
    rankA: '#19',
    recordA: '23-1-0 ',
    weight: '155',
    recordB: ' 14-4-0',
    rankB: '#47',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/50888-magomed-mustafaev',
    fighterB: 'Magomed Mustafaev'
  },
  {
    fighterA: 'Tagir Ulanbekov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/130955-tagir-ulanbekov',
    rankA: '#17',
    recordA: '12-1-0 ',
    weight: '125',
    recordB: ' 18-5-0',
    rankB: '#32',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/30534-alan-nascimento',
    fighterB: 'Allan Nascimento'
  }
]
,"UFC 267",
"9",
"ESPN+"
],
["Ultimate Fighting Championship",
1636254000000,
'',
[
  {
    fighterA: 'Kamaru Usman',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/39265-kamarudeen-usman',
    rankA: '#1',
    recordA: '19-1-0 ',
    weight: '170',
    recordB: ' 16-2-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/23634-colby-covington',
    fighterB: 'Colby Covington'
  },
  {
    fighterA: 'Rose Namajunas',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/39227-rose-namajunas-the-riveter',
    rankA: '#1',
    recordA: '10-4-0 ',
    weight: '115',
    recordB: ' 21-2-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/83443-weili-zhang',
    fighterB: 'Weili Zhang'
  },
  {
    fighterA: 'Justin Gaethje',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/16421-justin-gaethje',
    rankA: '#3',
    recordA: '22-3-0 ',
    weight: '155',
    recordB: ' 22-6-0',
    rankB: '#5',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/mike-chandler',
    fighterB: 'Michael Chandler'
  },
  {
    fighterA: 'Frankie Edgar',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/frankie-edgar-the-answer',
    rankA: '#11',
    recordA: '24-9-1 ',
    weight: '135',
    recordB: ' 19-7-1',
    rankB: '#13',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/48144-marlon-vera-chito',
    fighterB: 'Marlon Vera'
  },
  {
    fighterA: 'Shane Burgos',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37627-shane-burgos',
    rankA: '#14',
    recordA: '13-3-0 ',
    weight: '145',
    recordB: ' 16-3-0',
    rankB: '#30',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/42701-billy-quarantillo',
    fighterB: 'Billy Quarantillo'
  },
  {
    fighterA: 'Edmen Shahbazyan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/142325-edmen-shahbazyan',
    rankA: '#15',
    recordA: '11-2-0 ',
    weight: '185',
    recordB: ' 10-3-0',
    rankB: '#22',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/125404-nassourdine-imavov',
    fighterB: 'Nassourdine Imavov'
  },
  {
    fighterA: 'Al Iaquinta',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/15047-al-iaquinta',
    rankA: '#22',
    recordA: '14-6-1 ',
    weight: '155',
    recordB: ' 27-12-1',
    rankB: '#21',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/bobby-green-king',
    fighterB: 'Bobby Green'
  },
  {
    fighterA: 'Andreas Michailidis',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/72348-andreas-mihalidis',
    rankA: '#75',
    recordA: '13-4-0 ',
    weight: '185',
    recordB: ' 3-1-0',
    rankB: '#105',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/117305-alex-pereira',
    fighterB: 'Alex Pereira'
  },
  {
    fighterA: 'Jordan Williams',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/73288-jordan-williams',
    rankA: '#129',
    recordA: '9-5-0 ',
    weight: '170',
    recordB: ' 7-0-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/171377-ian-garry',
    fighterB: 'Ian Garry'
  },
  {
    fighterA: 'C.J. Vergara',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/38340-carlos-vergara',
    rankA: '#2',
    recordA: '9-2-1 ',
    weight: '125',
    recordB: ' 9-4-0',
    rankB: '#40',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/50154-ode-osbourne',
    fighterB: 'Ode Osbourne'
  },
  {
    fighterA: 'Gian Villante',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/gian-villante',
    rankA: '#114',
    recordA: '17-13-0 ',
    weight: '265',
    recordB: ' 21-7-0',
    rankB: '#99',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/8196-chris-barnett-beast-boy',
    fighterB: 'Chris Barnett'
  },
  {
    fighterA: 'Aleksa Camur',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90744-aleksa-camur',
    rankA: '#55',
    recordA: '6-2-0 ',
    weight: '205',
    recordB: ' 13-6-0',
    rankB: '#56',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/55658-john-allan',
    fighterB: 'John Allan'
  },
  {
    fighterA: 'Phil Hawes',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/63542-phil-hawes',
    rankA: '#30',
    recordA: '11-2-0 ',
    weight: '185',
    recordB: ' 26-8-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/14863-christopher-curtis-the-action-man',
    fighterB: 'Chris Curtis'
  }
]
,"UFC 268",
"8",
"Pay Per View | Prelims: ESPN"
],
["Ultimate Fighting Championship",
1636844400000,
'',
[
  {
    fighterA: 'Max Holloway',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/12723-max-holloway-lil-evil',
    rankA: '#2',
    recordA: '22-6-0 ',
    weight: '145',
    recordB: ' 13-2-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/70995-yair-rodriguez',
    fighterB: 'Yair Rodriguez'
  },
  {
    fighterA: 'Philipe Lins',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/9874-felipe-lins-felipao',
    rankA: '#45',
    recordA: '14-5-0 ',
    weight: '205',
    recordB: ' 25-16-0',
    rankB: '#64',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/ovince-st-preux',
    fighterB: 'Ovince St. Preux'
  },
  {
    fighterA: 'Ben Rothwell',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/ben-rothwell-northstar',
    rankA: '#20',
    recordA: '39-13-0 ',
    weight: '265',
    recordB: ' 18-7-1',
    rankB: '#31',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/marcos-rogerio-de-lima-pezao',
    fighterB: 'Marcos Rogério de Lima'
  },
  {
    fighterA: 'Kevin Holland',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/35757-kevin-holland',
    rankA: '#13',
    recordA: '21-7-0 ',
    weight: '185',
    recordB: ' 10-2-0',
    rankB: '#38',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/16027-kyle-daukaus',
    fighterB: 'Kyle Daukaus'
  },
  {
    fighterA: 'Cynthia Calvillo',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/25471-cynthia-calvillo',
    rankA: '#7',
    recordA: '9-3-1 ',
    weight: '125',
    recordB: ' 12-5-0',
    rankB: '#12',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/47916-andrea-lee',
    fighterB: 'Andrea Lee'
  },
  {
    fighterA: 'Felicia Spencer',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37314-felicia-spencer',
    rankA: '#3',
    recordA: '8-3-0 ',
    weight: '145',
    recordB: ' 5-1-0',
    rankB: '#27',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/71668-leah-letson-nidas',
    fighterB: 'Leah Letson'
  },
  {
    fighterA: 'Sean Woodson',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/103506-sean-woodson',
    rankA: '#45',
    recordA: '8-1-0 ',
    weight: '145',
    recordB: ' 8-2-0',
    rankB: '#111',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/119395-collin-anglin',
    fighterB: 'Collin Anglin'
  },
  {
    fighterA: 'Eryk Anders',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/30666-eryk-anders',
    rankA: '#38',
    recordA: '14-5-0 ',
    weight: '185',
    recordB: ' 9-1-0',
    rankB: '#47',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/147160-roman-dolidze',
    fighterB: 'Roman Dolidze'
  },
  {
    fighterA: 'Cortney Casey',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/21135-courtney-casey',
    rankA: '#34',
    recordA: '9-9-0 ',
    weight: '125',
    recordB: ' 8-4-0',
    rankB: '#44',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/116037-liana-dzhoudzhua',
    fighterB: 'Liana Jojua'
  },
  {
    fighterA: 'Yadong Song',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/47836-yadong-song',
    rankA: '#17',
    recordA: '17-5-1 ',
    weight: '135',
    recordB: ' 17-4-0',
    rankB: '#41',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/30552-julio-arce',
    fighterB: 'Julio Arce'
  },
  {
    fighterA: 'Thiago Moisés',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/49744-thiago-moiss',
    rankA: '#15',
    recordA: '15-5-0 ',
    weight: '155',
    recordB: ' 18-2-0',
    rankB: '#40',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/97013-joel-alvarez',
    fighterB: 'Joel Alvarez'
  },
  {
    fighterA: 'Kennedy Nzechukwu',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/119288-kennedy-nzechukwu',
    rankA: '#26',
    recordA: '9-1-0 ',
    weight: '205',
    recordB: ' 14-2-1',
    rankB: '#24',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/103262-da-un-jung',
    fighterB: 'Da Un Jung'
  },
  {
    fighterA: 'Miguel Baeza',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/99224-miguel-baeza',
    rankA: '#25',
    recordA: '10-1-0 ',
    weight: '170',
    recordB: ' 12-2-0',
    rankB: '#31',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/97154-kalinn-williams',
    fighterB: 'Khaos Williams'
  }
]
,"UFC Fight Night",
"8",
"ESPN+"
],
["Ultimate Fighting Championship",
1637449200000,
'',
[
  {
    fighterA: 'Ketlen Vieira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/99972-ketlen-vieira-fenomeno',
    rankA: '#7',
    recordA: '11-2-0 ',
    weight: '135',
    recordB: ' 19-7-0',
    rankB: '#11',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/miesha-tate-takedown',
    fighterB: 'Miesha Tate'
  },
  {
    fighterA: 'Michael Chiesa',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/15253-mike-chiesa-maverick',
    rankA: '#8',
    recordA: '17-5-0 ',
    weight: '170',
    recordB: ' 14-0-0',
    rankB: '#14',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/32242-sean-brady',
    fighterB: 'Sean Brady'
  },
  {
    fighterA: 'Adrian Yanez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/34063-adrian-yanez',
    rankA: '#30',
    recordA: '14-3-0 ',
    weight: '135',
    recordB: ' 11-5-0',
    rankB: '#32',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/18815-david-grant',
    fighterB: 'Davey Grant'
  },
  {
    fighterA: 'Joanne Calderwood',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/22500-joanne-calderwood',
    rankA: '#6',
    recordA: '15-6-0 ',
    weight: '125',
    recordB: ' 18-1-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/74022-taila-santos',
    fighterB: 'Taila Santos'
  },
  {
    fighterA: 'Cody Durden',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/68337-cody-durden',
    rankA: '#39',
    recordA: '11-3-1 ',
    weight: '125',
    recordB: ' 18-8-0',
    rankB: '#44',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/119560-aoriqileng',
    fighterB: 'Qileng Aori'
  },
  {
    fighterA: 'Cheyanne Buys',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/59694-cheyanne-vlismas',
    rankA: '#37',
    recordA: '6-2-0 ',
    weight: '115',
    recordB: ' 6-2-0',
    rankB: '#24',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/174166-looma-lookboonmee',
    fighterB: 'Loma Lookboonmee'
  },
  {
    fighterA: 'Terrance McKinney',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/126382-terrance-mckinney',
    rankA: '#39',
    recordA: '11-3-0 ',
    weight: '155',
    recordB: ' 12-3-0',
    rankB: '#60',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/119061-fares-ziam',
    fighterB: 'Fares Ziam'
  },
  {
    fighterA: 'Rafa García',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/105452-rafael-garcia-gifted',
    rankA: '#96',
    recordA: '12-2-0 ',
    weight: '155',
    recordB: ' 6-0-0',
    rankB: '#29',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/121270-natan-levy',
    fighterB: 'Natan Levy'
  },
  {
    fighterA: 'Azamat Murzakanov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/93373-azamat-murzakanov',
    rankA: '#17',
    recordA: '10-0-0 ',
    weight: '205',
    recordB: ' 15-5-0',
    rankB: '#31',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/51446-marcin-prachnio',
    fighterB: 'Marcin Prachnio'
  },
  {
    fighterA: 'Augusto Sakai',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/44468-augusto-sakai',
    rankA: '#11',
    recordA: '15-3-1 ',
    weight: '265',
    recordB: ' 13-3-0',
    rankB: '#14',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/120884-tai-tuivasa-bam-bam',
    fighterB: 'Tai Tuivasa'
  },
  {
    fighterA: 'Denys Bondar',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/104652-denis-bondar',
    rankA: '#2',
    recordA: '16-3-0 ',
    weight: '125',
    recordB: ' 13-5-0',
    rankB: '#20',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/36176-malcom-gordon',
    fighterB: 'Malcolm Gordon'
  },
  {
    fighterA: 'Jessica Penne',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/jessica-pene',
    rankA: '#19',
    recordA: '14-5-0 ',
    weight: '115',
    recordB: ' 9-1-0',
    rankB: '#23',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/152138-luana-pinheiro',
    fighterB: 'Luana Pinheiro'
  },
  {
    fighterA: 'Rani Yahya',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/rani-yahya',
    rankA: '#26',
    recordA: '27-10-1 ',
    weight: '135',
    recordB: ' 17-8-0',
    rankB: '#39',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/kyung-ho-kang',
    fighterB: 'Kyung Ho Kang'
  },
  {
    fighterA: 'Shayilan Nuerdanbieke',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/132976-yilan-sha',
    rankA: '#140',
    recordA: '19-7-0 ',
    weight: '145',
    recordB: ' 14-7-0',
    rankB: '#145',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/17490-sean-soriano',
    fighterB: 'Sean Soriano'
  },
  {
    fighterA: 'Tucker Lutz',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/39248-tucker-lutz',
    rankA: '#72',
    recordA: '12-1-0 ',
    weight: '145',
    recordB: ' 15-3-0',
    rankB: '#46',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/29210-pat-sabatini',
    fighterB: 'Pat Sabatini'
  }
]
,"UFC Fight Night",
"11",
"ESPN+"
],
["Ultimate Fighting Championship",
1638658800000,
'',
[
  {
    fighterA: 'Rob Font',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/rob-font',
    rankA: '#4',
    recordA: '19-4-0 ',
    weight: '135',
    recordB: ' 30-7-0',
    rankB: '#5',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/jose-aldo-junior',
    fighterB: 'José Aldo'
  },
  {
    fighterA: 'Rafael Fiziev',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/108035-rafael-fiziev',
    rankA: '#17',
    recordA: '10-1-0 ',
    weight: '155',
    recordB: ' 10-1-0',
    rankB: '#13',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/146061-brad-riddell-quake',
    fighterB: 'Brad Riddell'
  },
  {
    fighterA: 'Matt Brown',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/28-matt-brown-the-immortal',
    rankA: '#38',
    recordA: '23-18-0 ',
    weight: '170',
    recordB: ' 15-8-0',
    rankB: '#54',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/16876-bryan-barberena',
    fighterB: 'Bryan Barberena'
  },
  {
    fighterA: 'Claudio Puelles',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/53808-claudio-puelles',
    rankA: '#58',
    recordA: '10-2-0 ',
    weight: '155',
    recordB: ' 15-4-0',
    rankB: '#70',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/chris-gruetzemacher-gritz',
    fighterB: 'Chris Gruetzemacher'
  },
  {
    fighterA: 'Jimmy Crute',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/126283-jim-chute',
    rankA: '#13',
    recordA: '12-2-0 ',
    weight: '205',
    recordB: ' 8-1-0',
    rankB: '#15',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/120815-jamahal-hill',
    fighterB: 'Jamahal Hill'
  },
  {
    fighterA: 'Mallory Martin',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/66199-mallory-martin',
    rankA: '#34',
    recordA: '7-4-0 ',
    weight: '115',
    recordB: ' 10-2-0',
    rankB: '#28',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/78224-montserrat-conejo-ruiz-toquinha',
    fighterB: 'Montserrat Ruiz'
  },
  {
    fighterA: 'Brad Tavares',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/brad-tavares',
    rankA: '#12',
    recordA: '19-6-0 ',
    weight: '185',
    recordB: ' 17-4-0',
    rankB: '#14',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/91516-brendan-allen',
    fighterB: 'Brendan Allen'
  },
  {
    fighterA: 'Zhalgas Zhumagulov',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/82310-zhalgas-zhumagalov',
    rankA: '#15',
    recordA: '14-5-0 ',
    weight: '125',
    recordB: ' 16-6-0',
    rankB: '#13',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/70075-manel-kape-prodigio',
    fighterB: 'Manel Kape'
  },
  {
    fighterA: 'Tanner Boser',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/35149-tanner-boser',
    rankA: '#21',
    recordA: '20-8-1 ',
    weight: '265',
    recordB: ' 14-1-0',
    rankB: '#23',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/89112-sergey-pavlovich',
    fighterB: 'Sergei Pavlovich'
  },
  {
    fighterA: 'Louis Smolka',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/38968-louis-smolka-da-last-samurai',
    rankA: '#40',
    recordA: '17-7-0 ',
    weight: '135',
    recordB: ' 10-5-0',
    rankB: '#79',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/91401-vince-morales',
    fighterB: 'Vince Morales'
  },
  {
    fighterA: 'Jake Matthews',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/45260-jake-matthews',
    rankA: '#24',
    recordA: '17-5-0 ',
    weight: '170',
    recordB: ' 9-2-1',
    rankB: '#40',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/15782-jeremiah-wells',
    fighterB: 'Jeremiah Wells'
  },
  {
    fighterA: 'Clay Guida',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/clay-guida-the-carpenter',
    rankA: '#34',
    recordA: '36-21-0 ',
    weight: '155',
    recordB: ' 18-4-1',
    rankB: '#27',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/leonardo-santos',
    fighterB: 'Leonardo Santos'
  }
]
,"UFC Fight Night",
"9",
"ESPN+"
],
["Ultimate Fighting Championship",
1639278000000,
'',
[
  {
    fighterA: 'Charles Oliveira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/charles-oliveira-do-bronx',
    rankA: '#1',
    recordA: '31-8-0 ',
    weight: '155',
    recordB: ' 28-6-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/dustin-poirier-the-diamond',
    fighterB: 'Dustin Poirier'
  },
  {
    fighterA: 'Amanda Nunes',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/amanda-nunes-lioness-of-the-ring',
    rankA: '#35',
    recordA: '21-4-0 ',
    weight: '135',
    recordB: ' 10-4-0',
    rankB: '#4',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/julianna-pena-the-venezuelan-vixen',
    fighterB: 'Julianna Peña'
  },
  {
    fighterA: 'Kai Kara-France',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/24803-kaiwhare-kara-france',
    rankA: '#7',
    recordA: '22-9-0 ',
    weight: '125',
    recordB: ' 12-4-0',
    rankB: '#12',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/21780-cody-garbrandt-no-love',
    fighterB: 'Cody Garbrandt'
  },
  {
    fighterA: "Sean O'Malley",
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/68186-sean-omalley',
    rankA: '#15',
    recordA: '14-1-0 ',
    weight: '135',
    recordB: ' 21-3-0',
    rankB: '#18',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/80405-raulian-paiva',
    fighterB: 'Raulian Paiva'
  },
  {
    fighterA: 'Leon Edwards',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/21429-leon-edwards',
    rankA: '#3',
    recordA: '19-3-0 ',
    weight: '170',
    recordB: ' 35-15-0',
    rankB: '#7',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/jorge-masvidal-gamebred',
    fighterB: 'Jorge Masvidal'
  },
  {
    fighterA: 'Priscila Cachoeira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/128371-priscila-cachoeira',
    rankA: '#33',
    recordA: '10-3-0 ',
    weight: '125',
    recordB: ' 9-6-0',
    rankB: '#19',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/73142-gillian-robertson',
    fighterB: 'Gillian Robertson'
  },
  {
    fighterA: 'Randy Costa',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/65764-randy-costa',
    rankA: '#49',
    recordA: '6-2-0 ',
    weight: '135',
    recordB: ' 7-2-0',
    rankB: '#98',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/46792-tony-kelley',
    fighterB: 'Tony Kelley'
  },
  {
    fighterA: 'Dricus Du Plessis',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/51267-dricus-du-plessis-stilknocks',
    rankA: '#22',
    recordA: '16-2-0 ',
    weight: '185',
    recordB: ' 21-4-0',
    rankB: '#16',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/38116-andr-muniz-sergipano',
    fighterB: 'André Muniz'
  },
  {
    fighterA: 'Alex Perez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/alex-perez',
    rankA: '#5',
    recordA: '24-6-0 ',
    weight: '125',
    recordB: ' 15-6-0',
    rankB: '#121',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/29221-matt-schnell',
    fighterB: 'Matt Schnell'
  },
  {
    fighterA: 'Ryan Hall',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37328-ryan-hall',
    rankA: '#23',
    recordA: '8-2-0 ',
    weight: '145',
    recordB: ' 26-12-0',
    rankB: '#41',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/19491-darrick-minner',
    fighterB: 'Darrick Minner'
  },
  {
    fighterA: 'Pedro Munhoz',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/5243-pedro-munoz-pedrinho',
    rankA: '#8',
    recordA: '19-6-0 ',
    weight: '135',
    recordB: ' 23-3-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/dominick-cruz-the-dominator',
    fighterB: 'Dominick Cruz'
  },
  {
    fighterA: 'Geoff Neal',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/20058-geoffrey-neal',
    rankA: '#13',
    recordA: '13-4-0 ',
    weight: '170',
    recordB: ' 28-4-0',
    rankB: '#12',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/29349-santiago-ponzinibbio-el-rasta',
    fighterB: 'Santiago Ponzinibbio'
  },
  {
    fighterA: 'Maycee Barber',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/143925-maycee-barber',
    rankA: '#14',
    recordA: '9-2-0 ',
    weight: '125',
    recordB: ' 7-1-0',
    rankB: '#36',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/167460-erin-blanchfield',
    fighterB: 'Erin Blanchfield'
  },
  {
    fighterA: 'Josh Emmett',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/51295-josh-emmett',
    rankA: '#10',
    recordA: '16-2-0 ',
    weight: '145',
    recordB: ' 15-4-0',
    rankB: '#8',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/21178-dan-ige',
    fighterB: 'Dan Ige'
  }
]
,"UFC 269",
"9",
"Pay Per View | Prelims: ESPN"
],
["Ultimate Fighting Championship",
1639868400000,
'',
[
  {
    fighterA: 'Derrick Lewis',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/14023-derrick-lewis-the-black-beast',
    rankA: '#4',
    recordA: '25-8-0 ',
    weight: '265',
    recordB: ' 12-3-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/25880-christopher-daukaus',
    fighterB: 'Chris Daukaus'
  },
  {
    fighterA: 'Nina Nunes',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/11224-nina-ansaroff',
    rankA: '#12',
    recordA: '10-7-0 ',
    weight: '115',
    recordB: ' 10-1-1',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/87845-amanda-lemos-amandinha',
    fighterB: 'Amanda Lemos'
  },
  {
    fighterA: 'Gerald Meerschaert',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/6018-gerald-meerschaert-the-machine',
    rankA: '#20',
    recordA: '33-14-0 ',
    weight: '185',
    recordB: ' 24-4-1',
    rankB: '#93',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/30204-abusupiyan-magomedov-abus',
    fighterB: 'Abusupiyan Magomedov'
  },
  {
    fighterA: 'Darren Elkins',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/darren-elkins',
    rankA: '#22',
    recordA: '26-9-0 ',
    weight: '145',
    recordB: ' 27-12-0',
    rankB: '#18',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/cub-swanson',
    fighterB: 'Cub Swanson'
  },
  {
    fighterA: 'Raoni Barcelos',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/30448-raoni-barcellos',
    rankA: '#19',
    recordA: '16-2-0 ',
    weight: '135',
    recordB: ' 13-7-0',
    rankB: '#40',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/30581-trevin-jones',
    fighterB: 'Trevin Jones'
  },
  {
    fighterA: 'Anthony Hernandez',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/41538-anthony-hernandez',
    rankA: '#25',
    recordA: '8-2-0 ',
    weight: '185',
    recordB: ' 13-3-0',
    rankB: '#78',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/34864-dustin-stoltzfus',
    fighterB: 'Dustin Stoltzfus'
  },
  {
    fighterA: "Don'Tale Mayes",
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/46499-dontale-mayes',
    rankA: '#48',
    recordA: '8-4-0 ',
    weight: '265',
    recordB: ' 14-4-0',
    rankB: '#59',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/86139-josh-parisian',
    fighterB: 'Josh Parisian'
  },
  {
    fighterA: 'Raphael Assunção',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/raphael-assuncao',
    rankA: '#14',
    recordA: '27-8-0 ',
    weight: '135',
    recordB: ' 18-3-0',
    rankB: '#63',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/33229-ricky-simon',
    fighterB: 'Ricky Simón'
  },
  {
    fighterA: 'Matt Sayles',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/75678-matt-sayles-robo',
    rankA: '#98',
    recordA: '8-3-0 ',
    weight: '155',
    recordB: ' 8-1-0',
    rankB: '#78',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/90318-jordan-leavitt',
    fighterB: 'Jordan Leavitt'
  },
  {
    fighterA: 'Justin Tafa',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/152336-justin-tafa',
    rankA: '#51',
    recordA: '4-3-0 ',
    weight: '265',
    recordB: ' 7-4-0',
    rankB: '#119',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/24519-harry-hunsucker',
    fighterB: 'Harry Hunsucker'
  },
  {
    fighterA: 'Raquel Pennington',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/26224-raquel-pennington',
    rankA: '#6',
    recordA: '12-8-0 ',
    weight: '135',
    recordB: ' 9-2-0',
    rankB: '#15',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/37072-julia-avila',
    fighterB: 'Julia Avila'
  },
  {
    fighterA: 'Charles Jourdain',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/36724-charles-jourdain',
    rankA: '#37',
    recordA: '11-4-1 ',
    weight: '145',
    recordB: ' 17-8-0',
    rankB: '#46',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/116569-andre-ewell',
    fighterB: 'Andre Ewell'
  }
]
,"UFC Fight Night",
"7",
"ESPN+"
],
["Ultimate Fighting Championship",
1642287600000,
'',
[
  {
    fighterA: 'Calvin Kattar',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/calvin-kattar-the-boston-finisher',
    rankA: '#5',
    recordA: '22-5-0 ',
    weight: '145',
    recordB: ' 14-2-0',
    rankB: '#6',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/121253-giga-chikadze',
    fighterB: 'Giga Chikadze'
  },
  {
    fighterA: 'Katlyn Chookagian',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37760-katlyn-chookagian',
    rankA: '#2',
    recordA: '16-4-0 ',
    weight: '125',
    recordB: ' 19-7-1',
    rankB: '#4',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/19813-jennifer-maia',
    fighterB: 'Jennifer Maia'
  },
  {
    fighterA: 'Joaquin Buckley',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/55022-joaquin-buckley',
    rankA: '#40',
    recordA: '13-4-0 ',
    weight: '185',
    recordB: ' 11-4-0',
    rankB: '#42',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/59306-abdul-razak-alhassan',
    fighterB: 'Abdul Razak Alhassan'
  },
  {
    fighterA: 'Kleydson Rodrigues',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/147055-kleidison-rodrigues-kr',
    rankA: '#58',
    recordA: '7-1-0 ',
    weight: '125',
    recordB: ' 4-3-0',
    rankB: '#26',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/41908-zarrukh-adashev',
    fighterB: 'Zarrukh Adashev'
  },
  {
    fighterA: 'Joanderson Brito',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/98539-joanderson-brito-tubarao',
    rankA: '#2',
    recordA: '12-2-1 ',
    weight: '145',
    recordB: ' 14-6-0',
    rankB: '#66',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/25872-william-algeo-honey-badger',
    fighterB: 'Bill Algeo'
  },
  {
    fighterA: 'Brandon Royval',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/25031-brandon-royval',
    rankA: '#6',
    recordA: '12-6-0 ',
    weight: '125',
    recordB: ' 17-3-0',
    rankB: '#82',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/53276-rogrio-bontorin',
    fighterB: 'Rogério Bontorin'
  },
  {
    fighterA: 'Jasmine Jasudavicius',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/171056-jasmine-jasdavicious',
    rankA: '#1',
    recordA: '6-1-0 ',
    weight: '125',
    recordB: ' 7-4-0',
    rankB: '#31',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/166442-kay-hansen',
    fighterB: 'Kay Hansen'
  },
  {
    fighterA: 'Brian Kelleher',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/13751-Brian-Kelleher',
    rankA: '#47',
    recordA: '23-12-0 ',
    weight: '135',
    recordB: ' 9-2-0',
    rankB: '#36',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/147590-saidyokub-kakharamonov',
    fighterB: 'Saidyokub Kakhramonov'
  },
  {
    fighterA: 'Ramiz Brahimaj',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/129794-ramiz-brahimaj',
    rankA: '#73',
    recordA: '9-3-0 ',
    weight: '170',
    recordB: ' 20-10-0',
    rankB: '#55',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/court-mcgee-the-crusher',
    fighterB: 'Court McGee'
  },
  {
    fighterA: 'Ashley Yoder',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/81569-ashley-yoder',
    rankA: '#28',
    recordA: '8-8-0 ',
    weight: '125',
    recordB: ' 6-4-0',
    rankB: '#97',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/35907-vanessa-demopoulos',
    fighterB: 'Vanessa Demopoulos'
  },
  {
    fighterA: 'Chase Sherman',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/55773-chase-sherman',
    rankA: '#45',
    recordA: '15-8-0 ',
    weight: '265',
    recordB: ' 12-6-0',
    rankB: '#60',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/17087-jake-collier',
    fighterB: 'Jake Collier'
  },
  {
    fighterA: 'Dakota Bush',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/109057-dakota-bush',
    rankA: '#145',
    recordA: '8-3-0 ',
    weight: '155',
    recordB: ' 5-1-0',
    rankB: '#130',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/48692-vyacheslav-borshev',
    fighterB: 'Viacheslav Borshchev'
  }
]
,"UFC Fight Night",
"9",
"ESPN+"
],
["Ultimate Fighting Championship",
1642906800000,
'',
[
  {
    fighterA: "Francis N'Gannou",
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/64378-francis-ngannou',
    rankA: '#1',
    recordA: '16-3-0 ',
    weight: '265',
    recordB: ' 10-0-0',
    rankB: '#3',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/187819-cyril-gane-real-c',
    fighterB: 'Ciryl Gane'
  },
  {
    fighterA: 'Brandon Moreno',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/27833-brandon-moreno-the-assassin',
    rankA: '#1',
    recordA: '19-5-2 ',
    weight: '125',
    recordB: ' 20-2-1',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/76553-deiveson-alcantra-daico',
    fighterB: 'Deiveson Figueiredo'
  },
  {
    fighterA: 'Jared Cannonier',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/63163-jared-cannonier',
    rankA: '#4',
    recordA: '14-5-0 ',
    weight: '185',
    recordB: ' 23-7-0',
    rankB: '#3',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/Derek-Brunson',
    fighterB: 'Derek Brunson'
  },
  {
    fighterA: 'Greg Hardy',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/169557-greg-hardy',
    rankA: '#33',
    recordA: '7-4-0 ',
    weight: '265',
    recordB: ' 59-16-1',
    rankB: '#17',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/alexey-oleinik',
    fighterB: 'Aleksei Oleinik'
  },
  {
    fighterA: 'Rodolfo Vieira',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/148791-rodolfo-vieira-srour-the-black-belt-hunter',
    rankA: '#34',
    recordA: '8-1-0 ',
    weight: '185',
    recordB: ' 17-5-0',
    rankB: '#43',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/70129-wellington-turman-fofo',
    fighterB: 'Wellington Turman'
  },
  {
    fighterA: 'Cody Stamann',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/22124-cody-stamann',
    rankA: '#22',
    recordA: '19-4-1 ',
    weight: '135',
    recordB: ' 14-2-0',
    rankB: '#28',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/36038-said-nurmagomedov',
    fighterB: 'Said Nurmagomedov'
  },
  {
    fighterA: 'Michael Morales',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/164286-michael-morales',
    rankA: '#3',
    recordA: '12-0-0 ',
    weight: '170',
    recordB: ' 14-3-0',
    rankB: '#33',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/20072-trevin-giles',
    fighterB: 'Trevin Giles'
  },
  {
    fighterA: 'Matt Frevola',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/83149-matt-frevola',
    rankA: '#42',
    recordA: '8-3-1 ',
    weight: '155',
    recordB: ' 10-0-0',
    rankB: '#10',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/214582-genaro-valdez-el-rayadito',
    fighterB: 'Genaro Valdéz'
  },
  {
    fighterA: 'Viviane Araujo',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/106437-viviane-araujo-vivi',
    rankA: '#8',
    recordA: '10-3-0 ',
    weight: '125',
    recordB: ' 13-3-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/68972-alexa-grasso',
    fighterB: 'Alexa Grasso'
  },
  {
    fighterA: 'Tony Gravely',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/80780-tony-gravely-lamar',
    rankA: '#56',
    recordA: '21-7-0 ',
    weight: '135',
    recordB: ' 18-3-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/86764-saimon-oliveira',
    fighterB: 'Saimon Oliveira'
  },
  {
    fighterA: 'Poliana Botelho',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/72267-poliana-botelho',
    rankA: '#35',
    recordA: '8-4-0 ',
    weight: '125',
    recordB: ' 9-4-2',
    rankB: '#33',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/56388-ji-yun-kim',
    fighterB: 'Ji Yeon Kim'
  },
  {
    fighterA: 'Warlley Alves',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37561-warley-alves',
    rankA: '#35',
    recordA: '14-5-0 ',
    weight: '170',
    recordB: ' 10-2-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/119831-jack-della-maddalena',
    fighterB: 'Jack Della Maddalena'
  },
  {
    fighterA: 'Movsar Evloev',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/85897-movsar-evloev',
    rankA: '#13',
    recordA: '15-0-0 ',
    weight: '145',
    recordB: ' 11-0-0',
    rankB: '#15',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/129278-ilia-topuria',
    fighterB: 'Ilia Topuria'
  }
]
,"UFC 270",
"9",
"Pay Per View | Prelims: ESPN"
],
["Bellator MMA",
1636761600000,
'',
[
  {
    fighterA: 'Cris Cyborg',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/cristiane-santos-cyborg',
    rankA: '#1',
    recordA: '24-2-0 ',
    weight: '145',
    recordB: ' 7-4-0',
    rankB: '#13',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/66456-sinead-kavanagh',
    fighterB: 'Sinead Kavanagh'
  },
  {
    fighterA: 'Tyrell Fortune',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/141665-tyrell-fortune',
    rankA: '#40',
    recordA: '11-1-0 ',
    weight: '265',
    recordB: ' 21-8-0',
    rankB: '#36',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/13890-Linton-Vassell',
    fighterB: 'Linton Vassell'
  },
  {
    fighterA: 'Arlene Blencowe',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/46970-arlene-blencowe-angerfist',
    rankA: '#6',
    recordA: '14-8-0 ',
    weight: '145',
    recordB: ' 9-3-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/60007-pam-sorenson-bam',
    fighterB: 'Pam Sorenson'
  },
  {
    fighterA: 'Aaron Pico',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/86018-aaron-pico',
    rankA: '#80',
    recordA: '8-3-0 ',
    weight: '145',
    recordB: ' 12-0-0',
    rankB: '#1',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/45007-justin-gonzales',
    fighterB: 'Justin Gonzales'
  },
  {
    fighterA: 'Steve Mowry',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/32133-steve-mowry',
    rankA: '#79',
    recordA: '9-0-0 ',
    weight: '265',
    recordB: ' 22-13-1',
    rankB: '#32',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/14025-rankim-cleveland',
    fighterB: 'Rakim Cleveland'
  },
  {
    fighterA: 'Jordan Newman',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/191727-jordan-newman',
    rankA: '#165',
    recordA: '3-0-0 ',
    weight: '185',
    recordB: ' 4-2-0',
    rankB: '#450',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/65703-shane-oshea',
    fighterB: "Shane O'Shea"
  },
  {
    fighterA: 'Valerie Loureda',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/186801-valerie-loureda',
    rankA: '#85',
    recordA: '3-1-0 ',
    weight: '125',
    recordB: ' 5-7-0',
    rankB: '#9',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/92396-taylor-miller',
    fighterB: 'Taylor Turner'
  },
  {
    fighterA: 'Cody Law',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/191893-cody-law',
    rankA: '#148',
    recordA: '4-0-0 ',
    weight: '145',
    recordB: ' 4-3-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/135951-colton-hamm',
    fighterB: 'Colton Hamm'
  },
  {
    fighterA: 'Roman Faraldo',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/186861-roman-feraldo',
    rankA: '#50',
    recordA: '5-0-0 ',
    weight: '170',
    recordB: ' 11-7-0',
    rankB: '#n/a',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/43103-robert-turnquest',
    fighterB: 'Robert Turnquest'
  },
  {
    fighterA: 'Bruna Ellen',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/94986-bruna-ellen',
    rankA: '#72',
    recordA: '5-3-0 ',
    weight: '125',
    recordB: ' 5-3-0',
    rankB: '#n/a',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/148205-desiree-yanez',
    fighterB: 'Desiree Yanez'
  }
]
,"Bellator 271",
"5",
"Showtime"
],
["Bellator MMA",
1636137000000,
'',
[
  {
    fighterA: 'Peter Queally',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/21195-peter-quelly',
    rankA: '#97',
    recordA: '13-5-1 ',
    weight: '155',
    recordB: ' 23-10-0',
    rankB: '#69',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/patricky-freire-pitbull',
    fighterB: 'Patricky Pitbull'
  },
  {
    fighterA: 'James Gallagher',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/69151-james-gallagher',
    rankA: '#105',
    recordA: '11-1-0 ',
    weight: '135',
    recordB: ' 14-1-0',
    rankB: '#62',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/64036-patrick-mix',
    fighterB: 'Patchy Mix'
  },
  {
    fighterA: 'Daniel Weichel',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/daniel-weichel',
    rankA: '#86',
    recordA: '41-12-0 ',
    weight: '145',
    recordB: ' 11-5-0',
    rankB: '#119',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/126006-pedro-carvalho',
    fighterB: 'Pedro Carvalho'
  },
  {
    fighterA: 'Daniele Scatizzi',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/100332-daniele-scatizzi-scat',
    rankA: '#27',
    recordA: '10-5-0 ',
    weight: '155',
    recordB: ' 16-7-0',
    rankB: '#23',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/56065-brian-hooi',
    fighterB: 'Brian Hooi'
  },
  {
    fighterA: 'Ciaran Clarke',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/55691-ciaran-clarke',
    rankA: '#220',
    recordA: '3-0-0 ',
    weight: '145',
    recordB: ' 6-1-1',
    rankB: '#35',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/59776-jordan-barton',
    fighterB: 'Jordan Barton'
  },
  {
    fighterA: 'Danni Neilan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/144402-danni-neilan',
    rankA: '#120',
    recordA: '4-0-0 ',
    weight: '115',
    recordB: ' 7-5-0',
    rankB: '#20',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/56046-audrey-kerouche-sorel',
    fighterB: 'Audrey Kerouche'
  },
  {
    fighterA: 'Junior Morgan',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/66314-junior-morgan',
    rankA: '#22',
    recordA: '3-0-0 ',
    weight: '145',
    recordB: ' 0-0-0',
    rankB: '#2',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/182192-darragh-kelly',
    fighterB: 'Darragh Kelly'
  },
  {
    fighterA: 'Stephen Costello',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/166041-stephen-costello',
    rankA: '#70',
    recordA: '0-0-0 ',
    weight: '170',
    recordB: ' 0-0-0',
    rankB: '#',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/307164-yusuf-nazokatov',
    fighterB: 'Yusuf Nazokatov'
  },
  {
    fighterA: 'Ilias Bulaid',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/123111-ilias-bulaid',
    rankA: '#',
    recordA: '2-0-0 ',
    weight: '145',
    recordB: ' 5-1-0',
    rankB: '#130',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/133560-georges-sasu',
    fighterB: 'Georges Sasu'
  },
  {
    fighterA: 'Ashley Reece',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/65808-ashley-reece',
    rankA: '#125',
    recordA: '8-2-0 ',
    weight: '170',
    recordB: ' 6-1-0',
    rankB: '#37',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/29663-luca-poclit',
    fighterB: 'Luca Poclit'
  },
  {
    fighterA: 'Lee Chadwick',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/5278-lee-chadwick',
    rankA: '#128',
    recordA: '26-15-1 ',
    weight: '205',
    recordB: ' 15-4-0',
    rankB: '#',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/13356-arunas-andriuskevicus',
    fighterB: 'Arunas Andriuskevicus'
  },
  {
    fighterA: 'Nicolò Solli',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/157077-nicolo-solli',
    rankA: '#82',
    recordA: '3-1-0 ',
    weight: '170',
    recordB: ' 5-0-0',
    rankB: '#123',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/59775-bobby-pallett',
    fighterB: 'Bobby Pallett'
  },
  {
    fighterA: 'Asaël Adjoudj',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/202606-asael-adjoudj',
    rankA: '#25',
    recordA: '2-1-0 ',
    weight: '145',
    recordB: ' 4-1-0',
    rankB: '#n/a',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/87308-keir-harvie',
    fighterB: 'Keir Harvie'
  },
  {
    fighterA: 'Gokhan Saricam',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/203358-gokhan-saricam',
    rankA: '#60',
    recordA: '5-1-0 ',
    weight: '265',
    recordB: ' 5-2-0',
    rankB: '#n/a',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/92676-rob-beech',
    fighterB: 'Rob Beech'
  },
  {
    fighterA: 'Fabian Edwards',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/106608-fabian-edwards',
    rankA: '#n/a',
    recordA: '9-2-0 ',
    weight: '185',
    recordB: ' 9-4-0',
    rankB: '#n/a',
    fighterBLink: 'https://www.tapology.com/fightcenter/fighters/66418-charlie-ward',
    fighterB: 'Charlie Ward'
  }
]
,"Bellator 270",
"12",
"Showtime"
],
["Ultimate Fighting Championship",
1635008400000,
'',
[
  {
    fighterA: 'Marvin Vettori ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/50533-marvin-vettori',
    rankA: '#n/a',
    recordA: '',
    weight: '205',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Paulo Costa'
  },
  {
    fighterA: 'Grant Dawson ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/32750-grant-dawson',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Ricky Glenn'
  },
  {
    fighterA: 'Jessica-Rose Clark ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/41689-jessy-rose',
    rankA: '#n/a',
    recordA: '',
    weight: '135',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Joselyne Edwards'
  },
  {
    fighterA: 'Alex Caceres ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/alex-caceres-bruce-leroy',
    rankA: '#n/a',
    recordA: '',
    weight: '145',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Seung Woo Choi'
  },
  {
    fighterA: 'Francisco Trinaldo ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/4609-francisco-drinaldo-massaranduba',
    rankA: '#n/a',
    recordA: '',
    weight: '170',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Dwight Grant'
  },
  {
    fighterA: 'Nick Negumereanu ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/142000-nick-negumereanu',
    rankA: '#n/a',
    recordA: '',
    weight: '205',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Ike Villanueva'
  },
  {
    fighterA: 'Gregory Rodrigues ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/78681-gregory-rodrigues-robocop',
    rankA: '#n/a',
    recordA: '',
    weight: '185',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Jun Yong Park'
  },
  {
    fighterA: 'Mason Jones ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/168430-mason-jones-the-dragon',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' David Onama'
  },
  {
    fighterA: 'Tabatha Ricci ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/81538-tabatha-ricci',
    rankA: '#n/a',
    recordA: '',
    weight: '115',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Maria Oliveira'
  },
  {
    fighterA: 'Jamie Pickett ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/38304-jamie-pickett',
    rankA: '#n/a',
    recordA: '',
    weight: '185',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Laureano Staropoli'
  },
  {
    fighterA: 'Jai Herbert ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/70002-jai-herbert',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Khama Worthy'
  },
  {
    fighterA: 'Jeff Molina ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/117845-jeffrey-molina',
    rankA: '#n/a',
    recordA: '',
    weight: '125',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Daniel da Silva'
  },
  {
    fighterA: 'Randa Markos ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/20984-randa-markos',
    rankA: '#n/a',
    recordA: '',
    weight: '115',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Livinha Souza'
  },
  {
    fighterA: 'Jonathan Martinez ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/41237-jonathon-martinez',
    rankA: '#n/a',
    recordA: '',
    weight: '135',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Zviad Lazishvili'
  }
]
,"UFC Fight Night",
"8",
"ESPN+"
],
["Bellator MMA",
1635006600000,
'',
[
  {
    fighterA: 'Fedor Emelianenko ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/fedor-emelianenko-the-last-emperor',
    rankA: '#n/a',
    recordA: '',
    weight: '265',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Tim Johnson'
  },
  {
    fighterA: 'Said Sowma ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/183184-said-sowma',
    rankA: '#n/a',
    recordA: '',
    weight: '265',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Vitaly Minakov'
  },
  {
    fighterA: 'Usman Nurmagomedov ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/194617-osman-nurmagomedov',
    rankA: '#n/a',
    recordA: '',
    weight: '160',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Patrik Pietilä'
  },
  {
    fighterA: 'Anatoly Tokov ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/37714-anatoly-tokov',
    rankA: '#n/a',
    recordA: '',
    weight: '185',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Sharaf Davlatmurodov'
  },
  {
    fighterA: 'Kirill Sidelnikov ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/kirill-sidelnikov-baby-fedor',
    rankA: '#n/a',
    recordA: '',
    weight: '265',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Rab Truesdale'
  },
  {
    fighterA: 'Katarzyna Sadura ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/90407-katarzyna-sadura',
    rankA: '#n/a',
    recordA: '',
    weight: '125',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Darina Mazdyuk'
  },
  {
    fighterA: 'Irina Alekseeva ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/213675-irina-alekseeva',
    rankA: '#n/a',
    recordA: '',
    weight: '130',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Stéphanie Page'
  },
  {
    fighterA: 'Nikita Mikhailov ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/151899-nikita-mikhailov',
    rankA: '#n/a',
    recordA: '',
    weight: '135',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Brian Moore'
  },
  {
    fighterA: 'Alexey Shurkevich ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/82308-alexei-shurkevich',
    rankA: '#n/a',
    recordA: '',
    weight: '170',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Grachik Bozinyan'
  },
  {
    fighterA: 'Aiden Lee ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/68589-aiden-lee',
    rankA: '#n/a',
    recordA: '',
    weight: '147',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Aleksandr Osetrov'
  }
]
,"Bellator 269",
"6",
"Showtime"
],
["Professional Fighters League",
1635366600000,
'',
[
  {
    fighterA: 'Kayla Harrison ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/34265-kayla-harrison',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Taylor Guardado'
  },
  {
    fighterA: 'Ray Cooper III ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/21174-ray-cooper-iii-braddah-boy',
    rankA: '#n/a',
    recordA: '',
    weight: '170',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Magomed Magomedkerimov'
  },
  {
    fighterA: 'Abby Montes ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/236512-abigail-montes',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Claressa Shields'
  },
  {
    fighterA: 'Bruno Cappelozza ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/24968-bruno-cappelozza',
    rankA: '#n/a',
    recordA: '',
    weight: '265',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Ante Delija'
  },
  {
    fighterA: 'Movlid Khaybulaev ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/68161-mavlidin-khaibulaev',
    rankA: '#n/a',
    recordA: '',
    weight: '145',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Chris Wade'
  },
  {
    fighterA: 'Antônio Carlos Júnior ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/54308-antnio-carlos-junior-cara-de-sapato',
    rankA: '#n/a',
    recordA: '',
    weight: '205',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Marthin Hamlet'
  },
  {
    fighterA: 'Raush Manfio ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/41763-raush-manfio',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Loik Radzhabov'
  },
  {
    fighterA: 'Jordan Young ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/40938-jordan-young',
    rankA: '#n/a',
    recordA: '',
    weight: '205',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Omari Akhmedov'
  },
  {
    fighterA: 'Julia Budd ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/julia-budd-the-jewel',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Kaitlin Young'
  },
  {
    fighterA: 'Don Madge ',
    fighterALink: 'https://www.tapology.com/fightcenter/fighters/17923-don-madge-magic-man',
    rankA: '#n/a',
    recordA: '',
    weight: '155',
    recordB: '',
    rankB: '#n/a',
    fighterBLink: null,
    fighterB: ' Nathan Williams'
  }
]
,"PFL 2021 #10",
"5",
"ESPN 2 | Prelims: ESPN+"
],
]
module.exports = data;
