let odds = [
  { name: "Ketlen Vieira", odds: "1.80" },
  { name: "Miesha Tate", odds: "2.05" },
  { name: "Michael Chiesa", odds: "2.30" },
  { name: "Sean Brady", odds: "1.67" },
  { name: "Kyung Ho Kang", odds: "1.87" },
  { name: "Rani Yahya", odds: "1.95" },
  { name: "Joanne Calderwood", odds: "3.50" },
  { name: "Taila Santos", odds: "1.31" },
  { name: "Adrian Yanez", odds: "1.36" },
  { name: "Davey Grant", odds: "3.25" },
  { name: "Pat Sabatini", odds: "1.71" },
  { name: "Tucker Lutz", odds: "2.20" },
  { name: "Natan Levy", odds: "2.00" },
  { name: "Rafa García", odds: "1.83" },
  { name: "Loma Lookboonmee", odds: "2.30" },
  { name: "Lupita Godinez", odds: "1.67" },
  { name: "Fares Ziam", odds: "1.95" },
  { name: "Terrance McKinney", odds: "1.87" },
  { name: "Cody Durden", odds: "1.69" },
  { name: "Qileng Aori", odds: "2.25" },
  { name: "Sean Soriano", odds: "1.36" },
  { name: "Shayilan Nuerdanbieke", odds: "3.20" },
  { name: "Luana Pinheiro", odds: "1.24" },
  { name: "Sam Hughes", odds: "4.20" },
  { name: "Jose Aldo", odds: "2.50" },
  { name: "Rob Font", odds: "1.59" },
  { name: "Brad Riddell", odds: "1.95" },
  { name: "Rafael Fiziev", odds: "1.87" },
  { name: "Jamahal Hill", odds: "2.50" },
  { name: "Jimmy Crute", odds: "1.59" },
  { name: "Bryan Barberena", odds: "1.56" },
  { name: "Matt Brown", odds: "2.55" },
  { name: "Jake Matthews", odds: "1.53" },
  { name: "Jeremiah Wells", odds: "2.60" },
  { name: "Chris Gruetzemacher", odds: "1.74" },
  { name: "Claudio Puelles", odds: "2.15" },
  { name: "Mallory Martin", odds: "1.61" },
  { name: "Montserrat Ruiz", odds: "2.45" },
  { name: "Manel Kape", odds: "1.48" },
  { name: "Zhalgas Zhumagulov", odds: "2.75" },
  { name: "Brad Tavares", odds: "1.95" },
  { name: "Brendan Allen", odds: "1.87" },
  { name: "Clay Guida", odds: "2.45" },
  { name: "Leo Santos", odds: "1.61" },
  { name: "Louis Smolka", odds: "1.74" },
  { name: "Vince Morales", odds: "2.15" },
  { name: "Last change: 4 min ago", odds: "1.31" },
  { name: "UFC 269December 11th", odds: "1.42" },
  { name: "Charles Oliveira", odds: "2.40" },
  { name: "Dustin Poirier", odds: "1.63" },
  { name: "Amanda Nunes", odds: "1.14" },
  { name: "Julianna Pena", odds: "6.00" },
  { name: "UFCDecember 31st", odds: "2.00" },
  { name: "Last change: 9 days ago", odds: "1.83" },
  { name: "Ciryl Gane", odds: "1.95" },
  { name: "Francis Ngannou", odds: "1.87" },
  { name: "Brandon Moreno", odds: "1.59" },
  { name: "Deiveson Figueiredo", odds: "2.50" },
  { name: "Natan Levy", odds: "1.87" },
  { name: "Rafa Garcia", odds: "1.95" },
  { name: "Pat Sabatini", odds: "1.63" },
  { name: "Tucker Lutz", odds: "2.40" },
  { name: "Amanda Nunes", odds: "1.14" },
  { name: "Julianna Pena", odds: "6.00" },
  { name: "Charles Oliveira", odds: "2.25" },
  { name: "Dustin Poirier", odds: "1.69" },
  {
    name: "UFC FIGHT NIGHT: LEWIS VS. DAUKAUSDecember 18th",
    odds: "NaN",
  },
  { name: "Last change: 1 day 1 hr ago", odds: "2.36" },
  { name: "KSWDecember 18th", odds: "2.16" },
  { name: "Last change: 4 days ago", odds: "1.59" },
  { name: "UFC 270January 22nd", odds: "2.50" },
  { name: "Ciryl Gane", odds: "1.95" },
  { name: "Francis Ngannou", odds: "1.87" },
  { name: "Brandon Moreno", odds: "1.59" },
  { name: "Deiveson Figueiredo", odds: "2.50" },
  { name: "Last change: 11 hr 58 min ago", odds: "6.20" },
  {
    name: "Home|Desktop site|Boxing Odds|Terms of service|18+|Responsible Gaming|BeGambleAware|Contact|© 2021",
    odds: "2.66",
  },
  { name: "Leon Edwards", odds: "1.51" },
  { name: "Charles Oliveira", odds: "2.34" },
  { name: "Dustin Poirier", odds: "1.63" },
  { name: "Chris Daukaus", odds: "1.74" },
  { name: "Derrick Lewis", odds: "2.16" },
  { name: "Israel Adesanya", odds: "1.44" },
  { name: "Robert Whittaker", odds: "2.88" },
  { name: "Ciryl Gane", odds: "2.00" },
  { name: "Francis Ngannou", odds: "1.85" },
  { name: "Brandon Moreno", odds: "1.62" },
  { name: "Deiveson Figueiredo", odds: "2.34" },
  { name: "Julianna Pena", odds: "6.20" },
  { name: "Jorge Masvidal", odds: "2.66" },
  { name: "Leon Edwards", odds: "1.51" },
  { name: "Charles Oliveira", odds: "2.34" },
  { name: "Dustin Poirier", odds: "1.63" },
  { name: "Chris Daukaus", odds: "1.74" },
  { name: "Derrick Lewis", odds: "2.16" },
  { name: "Israel Adesanya", odds: "1.44" },
  { name: "Robert Whittaker", odds: "2.88" },
  { name: "Ciryl Gane", odds: "2.00" },
  { name: "Francis Ngannou", odds: "1.85" },
  { name: "Brandon Moreno", odds: "1.62" },
  { name: "Deiveson Figueiredo", odds: "2.34" },
];
