let odds = [
{"name":"Kamuela Kirk" , "odds": "2.38"},
{"name":"Esteban Ribovics" , "odds": "1.67"},
{"name":"Shannon Ross" , "odds": "2.30"},
{"name":"Jesus Aguilar" , "odds": "1.73"},
{"name":"Cameron Saaiman" , "odds": "1.19"},
{"name":"Terrence Mitchell" , "odds": "5.50"},
{"name":"Vitor Petrino" , "odds": "1.43"},
{"name":"Marcin Prachnio" , "odds": "3.25"},
{"name":"Tatsuro Taira" , "odds": "1.13"},
{"name":"Edgar Chairez" , "odds": "8.00"},
{"name":"Jimmy Crute" , "odds": "1.80"},
{"name":"Alonzo Menifield" , "odds": "2.20"},
{"name":"Jack Della Maddalena" , "odds": "1.10"},
{"name":"Josiah Harrell" , "odds": "7.10"},
{"name":"Yazmin Jauregui" , "odds": "1.27"},
{"name":"Denise Gomes" , "odds": "4.00"},
{"name":"Robbie Lawler" , "odds": "3.00"},
{"name":"Niko Price" , "odds": "1.45"},
{"name":"Robert Whittaker" , "odds": "1.30"},
{"name":"Dricus Du Plessis" , "odds": "4.00"},
{"name":"Bo Nickal" , "odds": "1.06"},
{"name":"Valentine Woodburn" , "odds": "14.00"},
{"name":"Jalin Turner" , "odds": "1.36"},
{"name":"Dan Hooker" , "odds": "3.50"},
{"name":"Brandon Moreno" , "odds": "1.53"},
{"name":"Alexandre Pantoja" , "odds": "2.75"},
{"name":"Alexander Volkanovski" , "odds": "1.29"},
{"name":"Yair Rodriguez" , "odds": "4.10"},
{"name":"Jon Jones" , "odds": "1.31"},
{"name":"Stipe Miocic" , "odds": "3.60"},
{"name":"Albert Duraev" , "odds": "2.25"},
{"name":"Jun Yong Park" , "odds": "1.75"},
{"name":"Alexander Munoz" , "odds": "1.73"},
{"name":"Carl Deaton" , "odds": "2.20"},
{"name":"Ashlee Evans-Smith" , "odds": "2.30"},
{"name":"Ailin Perez" , "odds": "1.68"},
{"name":"Austin Lingo" , "odds": "2.63"},
{"name":"Melquizael Costa" , "odds": "1.53"},
{"name":"Evan Elder" , "odds": "1.36"},
{"name":"Genaro Valdez" , "odds": "3.50"},
{"name":"Istela Nunes" , "odds": "3.30"},
{"name":"Viktoriia Dudakova" , "odds": "1.36"},
{"name":"Terrance McKinney" , "odds": "2.25"},
{"name":"Nazim Sadykhov" , "odds": "1.70"},
{"name":"Tucker Lutz" , "odds": "2.75"},
{"name":"Melsik Baghdasaryan" , "odds": "1.50"},
{"name":"Tyson Nam" , "odds": "4.33"},
{"name":"Azat Maksum" , "odds": "1.29"},
{"name":"Norma Dumont" , "odds": "1.73"},
{"name":"Chelsea Chandler" , "odds": "2.30"},
{"name":"Ottman Azaitar" , "odds": "2.16"},
{"name":"Francisco Prado" , "odds": "1.80"},
{"name":"Walt Harris" , "odds": "1.53"},
{"name":"Josh Parisian" , "odds": "2.70"},
{"name":"Holly Holm" , "odds": "1.67"},
{"name":"Mayra Bueno Silva" , "odds": "2.40"},
{"name":"Tom Aspinall" , "odds": "1.25"},
{"name":"Marcin Tybura" , "odds": "4.50"},
{"name":"Derrick Lewis" , "odds": "2.00"},
{"name":"Marcos Rogerio de Lima" , "odds": "1.91"},
{"name":"Ikram Aliskerov" , "odds": "1.83"},
{"name":"Paulo Costa" , "odds": "2.00"},
{"name":"Jan Blachowicz" , "odds": "1.73"},
{"name":"Alex Pereira" , "odds": "2.28"},
{"name":"Kevin Holland" , "odds": "1.62"},
{"name":"Michael Chiesa" , "odds": "2.50"},
{"name":"Dustin Poirier" , "odds": "1.83"},
{"name":"Justin Gaethje" , "odds": "2.10"},
{"name":"Aljamain Sterling" , "odds": "1.37"},
{"name":"Sean OMalley" , "odds": "3.30"},
{"name":"Conor McGregor" , "odds": "1.91"},
{"name":"Michael Chandler" , "odds": "2.07"},
]
