let odds = [
{"name":"Arman Tsarukyan" , "odds": "1.13"},
{"name":"Joel Alvarez" , "odds": "5.50"},
{"name":"Ji Yeon Kim" , "odds": "1.57"},
{"name":"Priscila Cachoeira" , "odds": "8.50"},
{"name":"Misha Cirkunov" , "odds": "1.80"},
{"name":"Wellington Turman" , "odds": "2.44"},
{"name":"Islam Makhachev" , "odds": "1.13"},
{"name":"Bobby Green" , "odds": "8.00"},
{"name":"Alex Oliveira" , "odds": "3.00"},
{"name":"Kevin Holland" , "odds": "1.44"},
{"name":"Brian Kelleher" , "odds": "6.00"},
{"name":"Umar Nurmagomedov" , "odds": "1.18"},
{"name":"Bryce Mitchell" , "odds": "1.67"},
{"name":"Edson Barboza" , "odds": "2.30"},
{"name":"Devonte Smith" , "odds": "1.36"},
{"name":"Erick Gonzalez" , "odds": "3.25"},
{"name":"Dustin Jacoby" , "odds": "1.57"},
{"name":"Michar Oleksiejczuk" , "odds": "2.38"},
{"name":"Greg Hardy" , "odds": "2.80"},
{"name":"Sergey Spivak" , "odds": "1.50"},
{"name":"Jailin Turner" , "odds": "1.73"},
{"name":"Jamie Mullarkey" , "odds": "2.10"},
{"name":"Jessica Eye" , "odds": "4.80"},
{"name":"Manon Fiorot" , "odds": "1.22"},
{"name":"Kennedy Nzechukwu" , "odds": "1.67"},
{"name":"Nick Negumereanu" , "odds": "2.20"},
{"name":"Marina Rodriguez" , "odds": "1.33"},
{"name":"Yan Xiaonan" , "odds": "3.50"},
{"name":"Mariya Agapova" , "odds": "1.50"},
{"name":"Maryna Moroz" , "odds": "2.80"},
{"name":"Tagir Ulanbekov" , "odds": "1.40"},
{"name":"Timothy Elliott" , "odds": "3.10"},
{"name":"Aljamain Sterling" , "odds": "3.80"},
{"name":"Petr Yan" , "odds": "1.30"},
{"name":"Rafael dos Anjos" , "odds": "3.10"},
{"name":"Rafael Fiziev" , "odds": "1.40"},
{"name":"Jorge Masvidal" , "odds": "4.00"},
{"name":"Colby Covington" , "odds": "1.33"},
{"name":"Diego Sanchez" , "odds": "6.50"},
{"name":"Kevin Lee" , "odds": "1.11"},
{"name":"AJ Fletcher" , "odds": "3.05"},
{"name":"Matthew Semelsberger" , "odds": "1.40"},
{"name":"Alex Caceres" , "odds": "2.90"},
{"name":"Sodiq Yusuff" , "odds": "1.45"},
{"name":"Alex Pereira" , "odds": "1.67"},
{"name":"Bruno Silva" , "odds": "2.30"},
{"name":"Azamat Murzakanov" , "odds": "1.73"},
{"name":"Tafon Nchukwi" , "odds": "2.15"},
{"name":"Cody Brundage" , "odds": "2.10"},
{"name":"Dalcha Lungiambula" , "odds": "1.75"},
{"name":"Damon Jackson" , "odds": "2.50"},
{"name":"Kamuela Kirk" , "odds": "1.62"},
{"name":"Drew Dober" , "odds": "1.40"},
{"name":"Ricky Glenn" , "odds": "3.00"},
{"name":"Guido Cannetti" , "odds": "2.05"},
{"name":"Kris Moutinho" , "odds": "1.83"},
{"name":"Javid Basharat" , "odds": "1.73"},
{"name":"Trevin Jones" , "odds": "2.20"},
{"name":"Karl Roberson" , "odds": "2.10"},
{"name":"Khalil Rountree" , "odds": "1.80"},
{"name":"Mandy Bohm" , "odds": "2.70"},
{"name":"Sabina Mazo" , "odds": "1.50"},
{"name":"Marlon Moraes" , "odds": "3.00"},
{"name":"Yadong Song" , "odds": "1.40"},
{"name":"Magomed Ankalaev" , "odds": "1.25"},
{"name":"Thiago Santos" , "odds": "4.80"},
{"name":"Arnold Allen" , "odds": "1.62"},
{"name":"Dan Hooker" , "odds": "2.25"},
{"name":"Nikita Krylov" , "odds": "1.67"},
{"name":"Paul Craig" , "odds": "2.20"},
{"name":"Paddy Pimblett" , "odds": "1.30"},
{"name":"Rodrigo Vargas" , "odds": "3.50"},
{"name":"Tom Aspinall" , "odds": "2.30"},
{"name":"Alexander Volkov" , "odds": "1.80"},
{"name":"Michelle Waterson" , "odds": "3.50"},
{"name":"Amanda Ribas" , "odds": "1.29"},
{"name":"Nate Landwehr" , "odds": "3.00"},
{"name":"Lerone Murphy" , "odds": "1.37"},
{"name":"Ian Garry" , "odds": "1.53"},
{"name":"Darian Weeks" , "odds": "2.50"},
{"name":"Alexander Volkanovski" , "odds": "1.25"},
{"name":"Chan Sung Jung" , "odds": "4.75"},
{"name":"Glover Teixeira" , "odds": "2.50"},
{"name":"Jiri Prochazka" , "odds": "1.57"},
{"name":"Charles Oliveira" , "odds": "1.67"},
{"name":"Justin Gaethje" , "odds": "2.30"},
{"name":"undefined" , "odds": "6.00"},
{"name":"undefined" , "odds": "2.40"},
{"name":"undefined" , "odds": "1.13"},
{"name":"undefined" , "odds": "4.00"},
{"name":"undefined" , "odds": "2.10"},
]
