let singleEvent = [
  [
    "Ultimate Fighting Championship",
    1635651000000,
    "",
    [
      {
        fighterA: "Glover Teixeira ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/glover-teixeira",
        rankA: "#n/a",
        recordA: "",
        weight: "205",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Jan Błachowicz",
      },
      {
        fighterA: "Petr Yan ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/90075-petr-yan",
        rankA: "#n/a",
        recordA: "",
        weight: "135",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Cory Sandhagen",
      },
      {
        fighterA: "Islam Makhachev ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/40148-islam-makhachev",
        rankA: "#n/a",
        recordA: "",
        weight: "155",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Dan Hooker",
      },
      {
        fighterA: "Alexander Volkov ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/alexander-volkov",
        rankA: "#n/a",
        recordA: "",
        weight: "265",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Marcin Tybura",
      },
      {
        fighterA: "Khamzat Chimaev ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/188143-khamzat-girikhanov",
        rankA: "#n/a",
        recordA: "",
        weight: "170",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Jingliang Li",
      },
      {
        fighterA: "Magomed Ankalaev ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/83405-magomed-ankalaev",
        rankA: "#n/a",
        recordA: "",
        weight: "205",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Volkan Oezdemir",
      },
      {
        fighterA: "Amanda Ribas ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/74330-amanda-ribas",
        rankA: "#n/a",
        recordA: "",
        weight: "115",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Virna Jandiroba",
      },
      {
        fighterA: "Zubaira Tukhugov ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/33555-zubair-tukhugov",
        rankA: "#n/a",
        recordA: "",
        weight: "145",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Ricardo Ramos",
      },
      {
        fighterA: "Albert Duraev ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/18658-albert-duraev",
        rankA: "#n/a",
        recordA: "",
        weight: "185",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Roman Kopylov",
      },
      {
        fighterA: "Elizeu Zaleski ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/28131-elizeu-zaleski-capoeira",
        rankA: "#n/a",
        recordA: "",
        weight: "170",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Benoit Saint-Denis",
      },
      {
        fighterA: "Michał Oleksiejczuk ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/61212-michal-oleksiejczuk",
        rankA: "#n/a",
        recordA: "",
        weight: "205",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Shamil Gamzatov",
      },
      {
        fighterA: "Lerone Murphy ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/84753-lerone-murphy",
        rankA: "#n/a",
        recordA: "",
        weight: "145",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Makwan Amirkhani",
      },
      {
        fighterA: "Andre Petroski ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/123353-andre-petroski",
        rankA: "#n/a",
        recordA: "",
        weight: "185",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Yaozong Hu",
      },
      {
        fighterA: "Tagir Ulanbekov ",
        fighterALink:
          "https://www.tapology.com/fightcenter/fighters/130955-tagir-ulanbekov",
        rankA: "#n/a",
        recordA: "",
        weight: "125",
        recordB: "",
        rankB: "#n/a",
        fighterBLink: null,
        fighterB: " Allan Nascimento",
      },
    ],
    "UFC 267",
    "8",
    "ESPN+",
  ],
];
module.exports = singleEvent;
